name: bookswithstatesrebuilder
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.6 <4.0.0'

dependencies:
  csv: ^5.1.1
  file_picker: ^6.1.1
  flutter:
    sdk: flutter
  states_rebuilder: ^6.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
