var vscodeSettings = '''
{
  "book": {
    "title": "Max",
    "description": "Beek"
  },
  "page":
[
{ "voorkant": "escape escape",         "achterkant": "workbench.action.exitZenMode",
                                     "extra": "inZenMode" },
{ "voorkant": "shift+escape",          "achterkant": "closeReferenceSearch",
                                     "extra": "inReferenceSearchEditor && !config.editor.stablePeek" },
{ "voorkant": "escape",                "achterkant": "closeReferenceSearch",
                                     "extra": "inReferenceSearchEditor && !config.editor.stablePeek" },
{ "voorkant": "shift+escape",          "achterkant": "cancelSelection",
                                     "extra": "editorHasSelection && textInputFocus" },
{ "voorkant": "escape",                "achterkant": "cancelSelection",
                                     "extra": "editorHasSelection && textInputFocus" },
{ "voorkant": "ctrl+end",              "achterkant": "cursorBottom",
                                     "extra": "textInputFocus" },
{ "voorkant": "ctrl+shift+end",        "achterkant": "cursorBottomSelect",
                                     "extra": "textInputFocus" },
{ "voorkant": "ctrl+shift+alt+down",   "achterkant": "cursorColumnSelectDown",
                                     "extra": "textInputFocus" },
{ "voorkant": "ctrl+shift+alt+left",   "achterkant": "cursorColumnSelectLeft",
                                     "extra": "textInputFocus" },
{ "voorkant": "ctrl+shift+alt+pagedown", "achterkant": "cursorColumnSelectPageDown",
                                     "extra": "textInputFocus" },
{ "voorkant": "ctrl+shift+alt+pageup", "achterkant": "cursorColumnSelectPageUp",
                                     "extra": "textInputFocus" },
{ "voorkant": "ctrl+shift+alt+right",  "achterkant": "cursorColumnSelectRight",
                                     "extra": "textInputFocus" },
{ "voorkant": "ctrl+shift+alt+up",     "achterkant": "cursorColumnSelectUp",
                                     "extra": "textInputFocus" },
{ "voorkant": "down",                  "achterkant": "cursorDown",
                                     "extra": "textInputFocus" },
{ "voorkant": "ctrl+shift+down",       "achterkant": "cursorDownSelect",
                                     "extra": "textInputFocus" },
{ "voorkant": "shift+down",            "achterkant": "cursorDownSelect",
                                     "extra": "textInputFocus" },
{ "voorkant": "end",                   "achterkant": "cursorEnd",
                                     "extra": "textInputFocus" },
{ "voorkant": "shift+end",             "achterkant": "cursorEndSelect",
                                     "extra": "textInputFocus" },
{ "voorkant": "home",                  "achterkant": "cursorHome",
                                     "extra": "textInputFocus" },
{ "voorkant": "shift+home",            "achterkant": "cursorHomeSelect",
                                     "extra": "textInputFocus" },
{ "voorkant": "left",                  "achterkant": "cursorLeft",
                                     "extra": "textInputFocus" },
{ "voorkant": "shift+left",            "achterkant": "cursorLeftSelect",
                                     "extra": "textInputFocus" },
{ "voorkant": "pagedown",              "achterkant": "cursorPageDown",
                                     "extra": "textInputFocus" },
{ "voorkant": "shift+pagedown",        "achterkant": "cursorPageDownSelect",
                                     "extra": "textInputFocus" },
{ "voorkant": "pageup",                "achterkant": "cursorPageUp",
                                     "extra": "textInputFocus" },
{ "voorkant": "shift+pageup",          "achterkant": "cursorPageUpSelect",
                                     "extra": "textInputFocus" },
{ "voorkant": "right",                 "achterkant": "cursorRight",
                                     "extra": "textInputFocus" },
{ "voorkant": "shift+right",           "achterkant": "cursorRightSelect",
                                     "extra": "textInputFocus" },
{ "voorkant": "ctrl+home",             "achterkant": "cursorTop",
                                     "extra": "textInputFocus" },
{ "voorkant": "ctrl+shift+home",       "achterkant": "cursorTopSelect",
                                     "extra": "textInputFocus" },
{ "voorkant": "up",                    "achterkant": "cursorUp",
                                     "extra": "textInputFocus" },
{ "voorkant": "ctrl+shift+up",         "achterkant": "cursorUpSelect",
                                     "extra": "textInputFocus" },
{ "voorkant": "shift+up",              "achterkant": "cursorUpSelect",
                                     "extra": "textInputFocus" },
{ "voorkant": "shift+backspace",       "achterkant": "deleteLeft",
                                     "extra": "textInputFocus" },
{ "voorkant": "backspace",             "achterkant": "deleteLeft",
                                     "extra": "textInputFocus" },
{ "voorkant": "delete",                "achterkant": "deleteRight",
                                     "extra": "textInputFocus" },
{ "voorkant": "ctrl+a",                "achterkant": "editor.action.selectAll",
                                     "extra": "textInputFocus" },
{ "voorkant": "ctrl+l",                "achterkant": "expandLineSelection",
                                     "extra": "textInputFocus" },
{ "voorkant": "shift+tab",             "achterkant": "outdent",
                                     "extra": "editorTextFocus && !editorReadonly && !editorTabMovesFocus" },
{ "voorkant": "ctrl+shift+z",          "achterkant": "redo",
                                     "extra": "textInputFocus && !editorReadonly" },
{ "voorkant": "ctrl+y",                "achterkant": "redo",
                                     "extra": "textInputFocus && !editorReadonly" },
{ "voorkant": "ctrl+down",             "achterkant": "scrollLineDown",
                                     "extra": "textInputFocus" },
{ "voorkant": "ctrl+up",               "achterkant": "scrollLineUp",
                                     "extra": "textInputFocus" },
{ "voorkant": "alt+pagedown",          "achterkant": "scrollPageDown",
                                     "extra": "textInputFocus" },
{ "voorkant": "alt+pageup",            "achterkant": "scrollPageUp",
                                     "extra": "textInputFocus" },
{ "voorkant": "tab",                   "achterkant": "tab",
                                     "extra": "editorTextFocus && !editorReadonly && !editorTabMovesFocus" },
{ "voorkant": "ctrl+z",                "achterkant": "undo",
                                     "extra": "textInputFocus && !editorReadonly" },
{ "voorkant": "shift+down",            "achterkant": "cursorColumnSelectDown",
                                     "extra": "editorColumnSelection && textInputFocus" },
{ "voorkant": "shift+left",            "achterkant": "cursorColumnSelectLeft",
                                     "extra": "editorColumnSelection && textInputFocus" },
{ "voorkant": "shift+pagedown",        "achterkant": "cursorColumnSelectPageDown",
                                     "extra": "editorColumnSelection && textInputFocus" },
{ "voorkant": "shift+pageup",          "achterkant": "cursorColumnSelectPageUp",
                                     "extra": "editorColumnSelection && textInputFocus" },
{ "voorkant": "shift+right",           "achterkant": "cursorColumnSelectRight",
                                     "extra": "editorColumnSelection && textInputFocus" },
{ "voorkant": "shift+up",              "achterkant": "cursorColumnSelectUp",
                                     "extra": "editorColumnSelection && textInputFocus" },
{ "voorkant": "shift+escape",          "achterkant": "removeSecondaryCursors",
                                     "extra": "editorHasMultipleSelections && textInputFocus" },
{ "voorkant": "escape",                "achterkant": "removeSecondaryCursors",
                                     "extra": "editorHasMultipleSelections && textInputFocus" },
{ "voorkant": "f12",                   "achterkant": "goToNextReference",
                                     "extra": "inReferenceSearchEditor || referenceSearchVisible" },
{ "voorkant": "f4",                    "achterkant": "goToNextReference",
                                     "extra": "inReferenceSearchEditor || referenceSearchVisible" },
{ "voorkant": "shift+f12",             "achterkant": "goToPreviousReference",
                                     "extra": "inReferenceSearchEditor || referenceSearchVisible" },
{ "voorkant": "shift+f4",              "achterkant": "goToPreviousReference",
                                     "extra": "inReferenceSearchEditor || referenceSearchVisible" },
{ "voorkant": "shift+enter",           "achterkant": "refactorPreview.apply",
                                     "extra": "refactorPreview.enabled && refactorPreview.enabled && refactorPreview.hasCheckedChanges && focusedView == 'refactorPreview'" },
{ "voorkant": "ctrl+f",                "achterkant": "actions.find" },
{ "voorkant": "enter",                 "achterkant": "breakpointWidget.action.acceptInput",
                                     "extra": "breakpointWidgetVisible && inBreakpointWidget" },
{ "voorkant": "shift+escape",          "achterkant": "closeBreakpointWidget",
                                     "extra": "breakpointWidgetVisible && textInputFocus" },
{ "voorkant": "escape",                "achterkant": "closeBreakpointWidget",
                                     "extra": "breakpointWidgetVisible && textInputFocus" },
{ "voorkant": "ctrl+u",                "achterkant": "cursorUndo",
                                     "extra": "textInputFocus" },
{ "voorkant": "ctrl+right",            "achterkant": "cursorWordEndRight",
                                     "extra": "textInputFocus" },
{ "voorkant": "ctrl+shift+right",      "achterkant": "cursorWordEndRightSelect",
                                     "extra": "textInputFocus" },
{ "voorkant": "ctrl+left",             "achterkant": "cursorWordStartLeft",
                                     "extra": "textInputFocus" },
{ "voorkant": "ctrl+shift+left",       "achterkant": "cursorWordStartLeftSelect",
                                     "extra": "textInputFocus" },
{ "voorkant": "ctrl+backspace",        "achterkant": "deleteWordLeft",
                                     "extra": "textInputFocus && !editorReadonly" },
{ "voorkant": "ctrl+delete",           "achterkant": "deleteWordRight",
                                     "extra": "textInputFocus && !editorReadonly" },
{ "voorkant": "ctrl+k ctrl+c",         "achterkant": "editor.action.addCommentLine",
                                     "extra": "editorTextFocus && !editorReadonly" },
{ "voorkant": "ctrl+d",                "achterkant": "editor.action.addSelectionToNextFindMatch",
                                     "extra": "editorFocus" },
{ "voorkant": "shift+alt+.",           "achterkant": "editor.action.autoFix",
                                     "extra": "editorTextFocus && !editorReadonly && supportedCodeAction" },
{ "voorkant": "shift+alt+a",           "achterkant": "editor.action.blockComment",
                                     "extra": "editorTextFocus && !editorReadonly" },
{ "voorkant": "ctrl+f2",               "achterkant": "editor.action.changeAll",
                                     "extra": "editorTextFocus && editorTextFocus && !editorReadonly" },
{ "voorkant": "ctrl+insert",           "achterkant": "editor.action.clipboardCopyAction",
                                     "extra": "textInputFocus" },
{ "voorkant": "ctrl+c",                "achterkant": "editor.action.clipboardCopyAction",
                                     "extra": "textInputFocus" },
{ "voorkant": "shift+delete",          "achterkant": "editor.action.clipboardCutAction",
                                     "extra": "textInputFocus && !editorReadonly" },
{ "voorkant": "ctrl+x",                "achterkant": "editor.action.clipboardCutAction",
                                     "extra": "textInputFocus && !editorReadonly" },
{ "voorkant": "shift+insert",          "achterkant": "editor.action.clipboardPasteAction",
                                     "extra": "textInputFocus && !editorReadonly" },
{ "voorkant": "ctrl+v",                "achterkant": "editor.action.clipboardPasteAction",
                                     "extra": "textInputFocus && !editorReadonly" },
{ "voorkant": "ctrl+/",                "achterkant": "editor.action.commentLine",
                                     "extra": "editorTextFocus && !editorReadonly" },
{ "voorkant": "shift+alt+down",        "achterkant": "editor.action.copyLinesDownAction",
                                     "extra": "editorTextFocus && !editorReadonly" },
{ "voorkant": "shift+alt+up",          "achterkant": "editor.action.copyLinesUpAction",
                                     "extra": "editorTextFocus && !editorReadonly" },
{ "voorkant": "ctrl+shift+z",          "achterkant": "editor.action.customEditor.redo",
                                     "extra": "focusedCustomEditorIsEditable && !inputFocus" },
{ "voorkant": "ctrl+y",                "achterkant": "editor.action.customEditor.redo",
                                     "extra": "focusedCustomEditorIsEditable && !inputFocus" },
{ "voorkant": "ctrl+z",                "achterkant": "editor.action.customEditor.undo",
                                     "extra": "focusedCustomEditorIsEditable && !inputFocus" },
{ "voorkant": "ctrl+k ctrl+k",         "achterkant": "editor.action.defineKeybinding",
                                     "extra": "editorTextFocus && !editorReadonly && editorLangId == 'jsonc'" },
{ "voorkant": "ctrl+shift+k",          "achterkant": "editor.action.deleteLines",
                                     "extra": "textInputFocus && !editorReadonly" },
{ "voorkant": "f7",                    "achterkant": "editor.action.diffReview.next",
                                     "extra": "isInDiffEditor" },
{ "voorkant": "shift+f7",              "achterkant": "editor.action.diffReview.prev",
                                     "extra": "isInDiffEditor" },
{ "voorkant": "alt+f3",                "achterkant": "editor.action.dirtydiff.next",
                                     "extra": "editorTextFocus" },
{ "voorkant": "shift+alt+f3",          "achterkant": "editor.action.dirtydiff.previous",
                                     "extra": "editorTextFocus" },
{ "voorkant": "enter",                 "achterkant": "editor.action.extensioneditor.findNext",
                                     "extra": "webviewFindWidgetFocused && !editorFocus && activeEditor == 'workbench.editor.extension'" },
{ "voorkant": "shift+enter",           "achterkant": "editor.action.extensioneditor.findPrevious",
                                     "extra": "webviewFindWidgetFocused && !editorFocus && activeEditor == 'workbench.editor.extension'" },
{ "voorkant": "ctrl+f",                "achterkant": "editor.action.extensioneditor.showfind",
                                     "extra": "!editorFocus && activeEditor == 'workbench.editor.extension'" },
{ "voorkant": "shift+alt+f",           "achterkant": "editor.action.formatDocument",
                                     "extra": "editorHasDocumentFormattingProvider && editorHasDocumentFormattingProvider && editorTextFocus && !editorReadonly" },
{ "voorkant": "shift+alt+f",           "achterkant": "editor.action.formatDocument.none",
                                     "extra": "editorTextFocus && !editorHasDocumentFormattingProvider && !editorHasDocumentFormattingProvider && !editorReadonly" },
{ "voorkant": "ctrl+k ctrl+f",         "achterkant": "editor.action.formatSelection",
                                     "extra": "editorHasDocumentSelectionFormattingProvider && editorHasDocumentSelectionFormattingProvider && editorTextFocus && !editorReadonly" },
{ "voorkant": "ctrl+f12",              "achterkant": "editor.action.goToImplementation",
                                     "extra": "editorHasImplementationProvider && editorTextFocus && !isInEmbeddedEditor" },
{ "voorkant": "shift+f12",             "achterkant": "editor.action.goToReferences",
                                     "extra": "editorHasReferenceProvider && editorTextFocus && !inReferenceSearchEditor && !isInEmbeddedEditor" },
{ "voorkant": "ctrl+shift+.",          "achterkant": "editor.action.inPlaceReplace.down",
                                     "extra": "editorTextFocus && !editorReadonly" },
{ "voorkant": "ctrl+shift+,",          "achterkant": "editor.action.inPlaceReplace.up",
                                     "extra": "editorTextFocus && !editorReadonly" },
{ "voorkant": "ctrl+]",                "achterkant": "editor.action.indentLines",
                                     "extra": "editorTextFocus && !editorReadonly" },
{ "voorkant": "ctrl+alt+up",           "achterkant": "editor.action.insertCursorAbove",
                                     "extra": "editorTextFocus" },
{ "voorkant": "shift+alt+i",           "achterkant": "editor.action.insertCursorAtEndOfEachLineSelected",
                                     "extra": "editorTextFocus" },
{ "voorkant": "ctrl+alt+down",         "achterkant": "editor.action.insertCursorBelow",
                                     "extra": "editorTextFocus" },
{ "voorkant": "ctrl+enter",            "achterkant": "editor.action.insertLineAfter",
                                     "extra": "editorTextFocus && !editorReadonly" },
{ "voorkant": "ctrl+shift+enter",      "achterkant": "editor.action.insertLineBefore",
                                     "extra": "editorTextFocus && !editorReadonly" },
{ "voorkant": "ctrl+shift+\\",         "achterkant": "editor.action.jumpToBracket",
                                     "extra": "editorTextFocus" },
{ "voorkant": "alt+f8",                "achterkant": "editor.action.marker.next",
                                     "extra": "editorFocus && !editorReadonly" },
{ "voorkant": "f8",                    "achterkant": "editor.action.marker.nextInFiles",
                                     "extra": "editorFocus && !editorReadonly" },
{ "voorkant": "shift+alt+f8",          "achterkant": "editor.action.marker.prev",
                                     "extra": "editorFocus && !editorReadonly" },
{ "voorkant": "shift+f8",              "achterkant": "editor.action.marker.prevInFiles",
                                     "extra": "editorFocus && !editorReadonly" },
{ "voorkant": "alt+down",              "achterkant": "editor.action.moveLinesDownAction",
                                     "extra": "editorTextFocus && !editorReadonly" },
{ "voorkant": "alt+up",                "achterkant": "editor.action.moveLinesUpAction",
                                     "extra": "editorTextFocus && !editorReadonly" },
{ "voorkant": "ctrl+k ctrl+d",         "achterkant": "editor.action.moveSelectionToNextFindMatch",
                                     "extra": "editorFocus" },
{ "voorkant": "f3",                    "achterkant": "editor.action.nextMatchFindAction",
                                     "extra": "editorFocus" },
{ "voorkant": "enter",                 "achterkant": "editor.action.nextMatchFindAction",
                                     "extra": "editorFocus && findInputFocussed" },
{ "voorkant": "ctrl+f3",               "achterkant": "editor.action.nextSelectionMatchFindAction",
                                     "extra": "editorFocus" },
{ "voorkant": "shift+alt+o",           "achterkant": "editor.action.organizeImports",
                                     "extra": "editorTextFocus && !editorReadonly && supportedCodeAction =~ /(\\s|)source\\.organizeImports" },
{ "voorkant": "ctrl+[",                "achterkant": "editor.action.outdentLines",
                                     "extra": "editorTextFocus && !editorReadonly" },
{ "voorkant": "alt+f12",               "achterkant": "editor.action.peekDefinition",
                                     "extra": "editorHasDefinitionProvider && editorTextFocus && !inReferenceSearchEditor && !isInEmbeddedEditor" },
{ "voorkant": "ctrl+shift+f12",        "achterkant": "editor.action.peekImplementation",
                                     "extra": "editorHasImplementationProvider && editorTextFocus && !inReferenceSearchEditor && !isInEmbeddedEditor" },
{ "voorkant": "shift+f3",              "achterkant": "editor.action.previousMatchFindAction",
                                     "extra": "editorFocus" },
{ "voorkant": "shift+enter",           "achterkant": "editor.action.previousMatchFindAction",
                                     "extra": "editorFocus && findInputFocussed" },
{ "voorkant": "ctrl+shift+f3",         "achterkant": "editor.action.previousSelectionMatchFindAction",
                                     "extra": "editorFocus" },
{ "voorkant": "ctrl+.",                "achterkant": "editor.action.quickFix",
                                     "extra": "editorHasCodeActionsProvider && editorTextFocus && !editorReadonly" },
{ "voorkant": "ctrl+shift+r",          "achterkant": "editor.action.refactor",
                                     "extra": "editorHasCodeActionsProvider && editorTextFocus && !editorReadonly" },
{ "voorkant": "ctrl+k ctrl+u",         "achterkant": "editor.action.removeCommentLine",
                                     "extra": "editorTextFocus && !editorReadonly" },
{ "voorkant": "f2",                    "achterkant": "editor.action.rename",
                                     "extra": "editorHasRenameProvider && editorTextFocus && !editorReadonly" },
{ "voorkant": "f12",                   "achterkant": "editor.action.revealDefinition",
                                     "extra": "editorHasDefinitionProvider && editorTextFocus && !isInEmbeddedEditor" },
{ "voorkant": "ctrl+k f12",            "achterkant": "editor.action.revealDefinitionAside",
                                     "extra": "editorHasDefinitionProvider && editorTextFocus && !isInEmbeddedEditor" },
{ "voorkant": "ctrl+shift+l",          "achterkant": "editor.action.selectHighlights",
                                     "extra": "editorFocus" },
{ "voorkant": "alt+f1",                "achterkant": "editor.action.showAccessibilityHelp",
                                     "extra": "editorFocus" },
{ "voorkant": "shift+f10",             "achterkant": "editor.action.showContextMenu",
                                     "extra": "textInputFocus" },
{ "voorkant": "ctrl+k ctrl+i",         "achterkant": "editor.action.showHover",
                                     "extra": "editorTextFocus" },
{ "voorkant": "shift+alt+right",       "achterkant": "editor.action.smartSelect.expand",
                                     "extra": "editorTextFocus" },
{ "voorkant": "shift+alt+left",        "achterkant": "editor.action.smartSelect.shrink",
                                     "extra": "editorTextFocus" },
{ "voorkant": "ctrl+h",                "achterkant": "editor.action.startFindReplaceAction" },
{ "voorkant": "ctrl+m",                "achterkant": "editor.action.toggleTabFocusMode" },
{ "voorkant": "alt+z",                 "achterkant": "editor.action.toggleWordWrap" },
{ "voorkant": "ctrl+shift+space",      "achterkant": "editor.action.triggerParameterHints",
                                     "extra": "editorHasSignatureHelpProvider && editorTextFocus" },
{ "voorkant": "ctrl+space",            "achterkant": "editor.action.triggerSuggest",
                                     "extra": "editorHasCompletionItemProvider && textInputFocus && !editorReadonly" },
{ "voorkant": "ctrl+k ctrl+x",         "achterkant": "editor.action.trimTrailingWhitespace",
                                     "extra": "editorTextFocus && !editorReadonly" },
{ "voorkant": "enter",                 "achterkant": "editor.action.webvieweditor.findNext",
                                     "extra": "webviewFindWidgetFocused && !editorFocus && activeEditor == 'WebviewEditor'" },
{ "voorkant": "shift+enter",           "achterkant": "editor.action.webvieweditor.findPrevious",
                                     "extra": "webviewFindWidgetFocused && !editorFocus && activeEditor == 'WebviewEditor'" },
{ "voorkant": "escape",                "achterkant": "editor.action.webvieweditor.hideFind",
                                     "extra": "webviewFindWidgetVisible && !editorFocus && activeEditor == 'WebviewEditor'" },
{ "voorkant": "ctrl+a",                "achterkant": "editor.action.webvieweditor.selectAll",
                                     "extra": "!editorFocus && !inputFocus && activeEditor == 'WebviewEditor'" },
{ "voorkant": "ctrl+f",                "achterkant": "editor.action.webvieweditor.showFind",
                                     "extra": "!editorFocus && activeEditor == 'WebviewEditor'" },
{ "voorkant": "f7",                    "achterkant": "editor.action.wordHighlight.next",
                                     "extra": "editorTextFocus && hasWordHighlights" },
{ "voorkant": "shift+f7",              "achterkant": "editor.action.wordHighlight.prev",
                                     "extra": "editorTextFocus && hasWordHighlights" },
{ "voorkant": "escape",                "achterkant": "editor.cancelOperation",
                                     "extra": "cancellableOperation" },
{ "voorkant": "ctrl+k ctrl+i",         "achterkant": "editor.debug.action.showDebugHover",
                                     "extra": "editorTextFocus && inDebugMode" },
{ "voorkant": "f9",                    "achterkant": "editor.debug.action.toggleBreakpoint",
                                     "extra": "editorTextFocus" },
{ "voorkant": "tab",                   "achterkant": "editor.emmet.action.expandAbbreviation",
                                     "extra": "config.emmet.triggerExpansionOnTab && editorTextFocus && !editorReadonly && !editorTabMovesFocus" },
{ "voorkant": "ctrl+shift+[",          "achterkant": "editor.fold",
                                     "extra": "editorTextFocus && foldingEnabled" },
{ "voorkant": "ctrl+k ctrl+0",         "achterkant": "editor.foldAll",
                                     "extra": "editorTextFocus && foldingEnabled" },
{ "voorkant": "ctrl+k ctrl+/",         "achterkant": "editor.foldAllBlockComments",
                                     "extra": "editorTextFocus && foldingEnabled" },
{ "voorkant": "ctrl+k ctrl+8",         "achterkant": "editor.foldAllMarkerRegions",
                                     "extra": "editorTextFocus && foldingEnabled" },
{ "voorkant": "ctrl+k ctrl+1",         "achterkant": "editor.foldLevel1",
                                     "extra": "editorTextFocus && foldingEnabled" },
{ "voorkant": "ctrl+k ctrl+2",         "achterkant": "editor.foldLevel2",
                                     "extra": "editorTextFocus && foldingEnabled" },
{ "voorkant": "ctrl+k ctrl+3",         "achterkant": "editor.foldLevel3",
                                     "extra": "editorTextFocus && foldingEnabled" },
{ "voorkant": "ctrl+k ctrl+4",         "achterkant": "editor.foldLevel4",
                                     "extra": "editorTextFocus && foldingEnabled" },
{ "voorkant": "ctrl+k ctrl+5",         "achterkant": "editor.foldLevel5",
                                     "extra": "editorTextFocus && foldingEnabled" },
{ "voorkant": "ctrl+k ctrl+6",         "achterkant": "editor.foldLevel6",
                                     "extra": "editorTextFocus && foldingEnabled" },
{ "voorkant": "ctrl+k ctrl+7",         "achterkant": "editor.foldLevel7",
                                     "extra": "editorTextFocus && foldingEnabled" },
{ "voorkant": "ctrl+k ctrl+[",         "achterkant": "editor.foldRecursively",
                                     "extra": "editorTextFocus && foldingEnabled" },
{ "voorkant": "f12",                   "achterkant": "editor.gotoNextSymbolFromResult",
                                     "extra": "hasSymbols" },
{ "voorkant": "escape",                "achterkant": "editor.gotoNextSymbolFromResult.cancel",
                                     "extra": "hasSymbols" },
{ "voorkant": "ctrl+k ctrl+l",         "achterkant": "editor.toggleFold",
                                     "extra": "editorTextFocus && foldingEnabled" },
{ "voorkant": "ctrl+shift+]",          "achterkant": "editor.unfold",
                                     "extra": "editorTextFocus && foldingEnabled" },
{ "voorkant": "ctrl+k ctrl+j",         "achterkant": "editor.unfoldAll",
                                     "extra": "editorTextFocus && foldingEnabled" },
{ "voorkant": "ctrl+k ctrl+9",         "achterkant": "editor.unfoldAllMarkerRegions",
                                     "extra": "editorTextFocus && foldingEnabled" },
{ "voorkant": "ctrl+k ctrl+]",         "achterkant": "editor.unfoldRecursively",
                                     "extra": "editorTextFocus && foldingEnabled" },
{ "voorkant": "tab",                   "achterkant": "insertSnippet",
                                     "extra": "editorTextFocus && hasSnippetCompletions && !editorTabMovesFocus && !inSnippetMode" },
{ "voorkant": "ctrl+enter",            "achterkant": "openReferenceToSide",
                                     "extra": "listFocus && referenceSearchVisible && !inputFocus" },
{ "voorkant": "enter",                 "achterkant": "repl.action.acceptInput",
                                     "extra": "inDebugRepl && textInputFocus" },
{ "voorkant": "ctrl+f",                "achterkant": "repl.action.filter",
                                     "extra": "inDebugRepl && textInputFocus" },
{ "voorkant": "escape",                "achterkant": "settings.action.clearSearchResults",
                                     "extra": "inSettingsSearch" },
{ "voorkant": "ctrl+.",                "achterkant": "settings.action.editFocusedSetting",
                                     "extra": "inSettingsSearch" },
{ "voorkant": "enter",                 "achterkant": "settings.action.focusNextSetting",
                                     "extra": "inSettingsSearch" },
{ "voorkant": "shift+enter",           "achterkant": "settings.action.focusPreviousSetting",
                                     "extra": "inSettingsSearch" },
{ "voorkant": "down",                  "achterkant": "settings.action.focusSettingsFile",
                                     "extra": "inSettingsSearch && !suggestWidgetVisible" },
{ "voorkant": "ctrl+f",                "achterkant": "settings.action.search",
                                     "extra": "inSettingsEditor" },
{ "voorkant": "ctrl+/",                "achterkant": "toggleExplainMode",
                                     "extra": "suggestWidgetVisible" },
{ "voorkant": "ctrl+k f2",             "achterkant": "togglePeekWidgetFocus",
                                     "extra": "inReferenceSearchEditor || referenceSearchVisible" },
{ "voorkant": "alt+f5",                "achterkant": "workbench.action.editor.nextChange",
                                     "extra": "editorTextFocus" },
{ "voorkant": "shift+alt+f5",          "achterkant": "workbench.action.editor.previousChange",
                                     "extra": "editorTextFocus" },
{ "voorkant": "shift+escape",          "achterkant": "workbench.action.hideComment",
                                     "extra": "commentEditorFocused" },
{ "voorkant": "escape",                "achterkant": "workbench.action.hideComment",
                                     "extra": "commentEditorFocused" },
{ "voorkant": "ctrl+enter",            "achterkant": "workbench.action.submitComment",
                                     "extra": "commentEditorFocused" },
{ "voorkant": "ctrl+left",             "achterkant": "cursorWordAccessibilityLeft",
                                     "extra": "accessibilityModeEnabled && textInputFocus" },
{ "voorkant": "ctrl+shift+left",       "achterkant": "cursorWordAccessibilityLeftSelect",
                                     "extra": "accessibilityModeEnabled && textInputFocus" },
{ "voorkant": "ctrl+right",            "achterkant": "cursorWordAccessibilityRight",
                                     "extra": "accessibilityModeEnabled && textInputFocus" },
{ "voorkant": "ctrl+shift+right",      "achterkant": "cursorWordAccessibilityRightSelect",
                                     "extra": "accessibilityModeEnabled && textInputFocus" },
{ "voorkant": "shift+escape",          "achterkant": "closeFindWidget",
                                     "extra": "editorFocus && findWidgetVisible" },
{ "voorkant": "escape",                "achterkant": "closeFindWidget",
                                     "extra": "editorFocus && findWidgetVisible" },
{ "voorkant": "ctrl+alt+enter",        "achterkant": "editor.action.replaceAll",
                                     "extra": "editorFocus && findWidgetVisible" },
{ "voorkant": "ctrl+shift+1",          "achterkant": "editor.action.replaceOne",
                                     "extra": "editorFocus && findWidgetVisible" },
{ "voorkant": "enter",                 "achterkant": "editor.action.replaceOne",
                                     "extra": "editorFocus && findWidgetVisible && replaceInputFocussed" },
{ "voorkant": "alt+enter",             "achterkant": "editor.action.selectAllMatches",
                                     "extra": "editorFocus && findWidgetVisible" },
{ "voorkant": "alt+c",                 "achterkant": "toggleFindCaseSensitive",
                                     "extra": "editorFocus" },
{ "voorkant": "alt+l",                 "achterkant": "toggleFindInSelection",
                                     "extra": "editorFocus" },
{ "voorkant": "alt+r",                 "achterkant": "toggleFindRegex",
                                     "extra": "editorFocus" },
{ "voorkant": "alt+w",                 "achterkant": "toggleFindWholeWord",
                                     "extra": "editorFocus" },
{ "voorkant": "tab",                   "achterkant": "jumpToNextSnippetPlaceholder",
                                     "extra": "editorTextFocus && hasNextTabstop && inSnippetMode" },
{ "voorkant": "shift+tab",             "achterkant": "jumpToPrevSnippetPlaceholder",
                                     "extra": "editorTextFocus && hasPrevTabstop && inSnippetMode" },
{ "voorkant": "escape",                "achterkant": "leaveEditorMessage",
                                     "extra": "messageVisible" },
{ "voorkant": "shift+escape",          "achterkant": "leaveSnippet",
                                     "extra": "editorTextFocus && inSnippetMode" },
{ "voorkant": "escape",                "achterkant": "leaveSnippet",
                                     "extra": "editorTextFocus && inSnippetMode" },
{ "voorkant": "shift+escape",          "achterkant": "closeDirtyDiff",
                                     "extra": "dirtyDiffVisible" },
{ "voorkant": "escape",                "achterkant": "closeDirtyDiff",
                                     "extra": "dirtyDiffVisible" },
{ "voorkant": "shift+escape",          "achterkant": "closeMarkersNavigation",
                                     "extra": "editorFocus && markersNavigationVisible" },
{ "voorkant": "escape",                "achterkant": "closeMarkersNavigation",
                                     "extra": "editorFocus && markersNavigationVisible" },
{ "voorkant": "shift+escape",          "achterkant": "closeParameterHints",
                                     "extra": "editorFocus && parameterHintsVisible" },
{ "voorkant": "escape",                "achterkant": "closeParameterHints",
                                     "extra": "editorFocus && parameterHintsVisible" },
{ "voorkant": "alt+down",              "achterkant": "showNextParameterHint",
                                     "extra": "editorFocus && parameterHintsMultipleSignatures && parameterHintsVisible" },
{ "voorkant": "down",                  "achterkant": "showNextParameterHint",
                                     "extra": "editorFocus && parameterHintsMultipleSignatures && parameterHintsVisible" },
{ "voorkant": "alt+up",                "achterkant": "showPrevParameterHint",
                                     "extra": "editorFocus && parameterHintsMultipleSignatures && parameterHintsVisible" },
{ "voorkant": "up",                    "achterkant": "showPrevParameterHint",
                                     "extra": "editorFocus && parameterHintsMultipleSignatures && parameterHintsVisible" },
{ "voorkant": "shift+tab",             "achterkant": "acceptAlternativeSelectedSuggestion",
                                     "extra": "suggestWidgetVisible && textInputFocus && textInputFocus" },
{ "voorkant": "shift+enter",           "achterkant": "acceptAlternativeSelectedSuggestion",
                                     "extra": "suggestWidgetVisible && textInputFocus && textInputFocus" },
{ "voorkant": "tab",                   "achterkant": "acceptSelectedSuggestion",
                                     "extra": "suggestWidgetVisible && textInputFocus" },
{ "voorkant": "enter",                 "achterkant": "acceptSelectedSuggestion",
                                     "extra": "acceptSuggestionOnEnter && suggestWidgetVisible && suggestionMakesTextEdit && textInputFocus" },
{ "voorkant": "shift+escape",          "achterkant": "hideSuggestWidget",
                                     "extra": "suggestWidgetVisible && textInputFocus" },
{ "voorkant": "escape",                "achterkant": "hideSuggestWidget",
                                     "extra": "suggestWidgetVisible && textInputFocus" },
{ "voorkant": "tab",                   "achterkant": "insertBestCompletion",
                                     "extra": "atEndOfWord && !hasOtherSuggestions && !inSnippetMode && !suggestWidgetVisible && config.editor.tabCompletion == 'on'" },
{ "voorkant": "tab",                   "achterkant": "insertNextSuggestion",
                                     "extra": "hasOtherSuggestions && textInputFocus && !inSnippetMode && !suggestWidgetVisible && config.editor.tabCompletion == 'on'" },
{ "voorkant": "shift+tab",             "achterkant": "insertPrevSuggestion",
                                     "extra": "hasOtherSuggestions && textInputFocus && !inSnippetMode && !suggestWidgetVisible && config.editor.tabCompletion == 'on'" },
{ "voorkant": "ctrl+pagedown",         "achterkant": "selectNextPageSuggestion",
                                     "extra": "suggestWidgetMultipleSuggestions && suggestWidgetVisible && textInputFocus" },
{ "voorkant": "pagedown",              "achterkant": "selectNextPageSuggestion",
                                     "extra": "suggestWidgetMultipleSuggestions && suggestWidgetVisible && textInputFocus" },
{ "voorkant": "ctrl+down",             "achterkant": "selectNextSuggestion",
                                     "extra": "suggestWidgetMultipleSuggestions && suggestWidgetVisible && textInputFocus" },
{ "voorkant": "down",                  "achterkant": "selectNextSuggestion",
                                     "extra": "suggestWidgetMultipleSuggestions && suggestWidgetVisible && textInputFocus" },
{ "voorkant": "ctrl+pageup",           "achterkant": "selectPrevPageSuggestion",
                                     "extra": "suggestWidgetMultipleSuggestions && suggestWidgetVisible && textInputFocus" },
{ "voorkant": "pageup",                "achterkant": "selectPrevPageSuggestion",
                                     "extra": "suggestWidgetMultipleSuggestions && suggestWidgetVisible && textInputFocus" },
{ "voorkant": "ctrl+up",               "achterkant": "selectPrevSuggestion",
                                     "extra": "suggestWidgetMultipleSuggestions && suggestWidgetVisible && textInputFocus" },
{ "voorkant": "up",                    "achterkant": "selectPrevSuggestion",
                                     "extra": "suggestWidgetMultipleSuggestions && suggestWidgetVisible && textInputFocus" },
{ "voorkant": "ctrl+space",            "achterkant": "toggleSuggestionDetails",
                                     "extra": "suggestWidgetVisible && textInputFocus" },
{ "voorkant": "ctrl+alt+space",        "achterkant": "toggleSuggestionFocus",
                                     "extra": "suggestWidgetVisible && textInputFocus" },
{ "voorkant": "enter",                 "achterkant": "acceptRenameInput",
                                     "extra": "editorFocus && renameInputVisible" },
{ "voorkant": "shift+enter",           "achterkant": "acceptRenameInputWithPreview",
                                     "extra": "config.editor.rename.enablePreview && editorFocus && renameInputVisible" },
{ "voorkant": "shift+escape",          "achterkant": "cancelRenameInput",
                                     "extra": "editorFocus && renameInputVisible" },
{ "voorkant": "escape",                "achterkant": "cancelRenameInput",
                                     "extra": "editorFocus && renameInputVisible" },
{ "voorkant": "ctrl+shift+l",          "achterkant": "addCursorsAtSearchResults",
                                     "extra": "fileMatchOrMatchFocus && searchViewletVisible" },
{ "voorkant": "ctrl+shift+;",          "achterkant": "breadcrumbs.focus",
                                     "extra": "breadcrumbsPossible" },
{ "voorkant": "ctrl+shift+.",          "achterkant": "breadcrumbs.focusAndSelect",
                                     "extra": "breadcrumbsPossible" },
{ "voorkant": "ctrl+right",            "achterkant": "breadcrumbs.focusNext",
                                     "extra": "breadcrumbsActive && breadcrumbsVisible" },
{ "voorkant": "right",                 "achterkant": "breadcrumbs.focusNext",
                                     "extra": "breadcrumbsActive && breadcrumbsVisible" },
{ "voorkant": "ctrl+left",             "achterkant": "breadcrumbs.focusPrevious",
                                     "extra": "breadcrumbsActive && breadcrumbsVisible" },
{ "voorkant": "left",                  "achterkant": "breadcrumbs.focusPrevious",
                                     "extra": "breadcrumbsActive && breadcrumbsVisible" },
{ "voorkant": "ctrl+enter",            "achterkant": "breadcrumbs.revealFocused",
                                     "extra": "breadcrumbsActive && breadcrumbsVisible" },
{ "voorkant": "space",                 "achterkant": "breadcrumbs.revealFocused",
                                     "extra": "breadcrumbsActive && breadcrumbsVisible" },
{ "voorkant": "ctrl+enter",            "achterkant": "breadcrumbs.revealFocusedFromTreeAside",
                                     "extra": "breadcrumbsActive && breadcrumbsVisible && listFocus && !inputFocus" },
{ "voorkant": "down",                  "achterkant": "breadcrumbs.selectFocused",
                                     "extra": "breadcrumbsActive && breadcrumbsVisible" },
{ "voorkant": "enter",                 "achterkant": "breadcrumbs.selectFocused",
                                     "extra": "breadcrumbsActive && breadcrumbsVisible" },
{ "voorkant": "ctrl+shift+.",          "achterkant": "breadcrumbs.toggleToOn",
                                     "extra": "!config.breadcrumbs.enabled" },
{ "voorkant": "shift+escape",          "achterkant": "closeAccessibilityHelp",
                                     "extra": "accessibilityHelpWidgetVisible && editorFocus" },
{ "voorkant": "escape",                "achterkant": "closeAccessibilityHelp",
                                     "extra": "accessibilityHelpWidgetVisible && editorFocus" },
{ "voorkant": "escape",                "achterkant": "closeReplaceInFilesWidget",
                                     "extra": "replaceInputBoxFocus && searchViewletVisible" },
{ "voorkant": "shift+alt+c",           "achterkant": "copyFilePath",
                                     "extra": "!editorFocus" },
{ "voorkant": "ctrl+k ctrl+shift+c",   "achterkant": "copyRelativeFilePath",
                                     "extra": "!editorFocus" },
{ "voorkant": "alt+enter",             "achterkant": "debug.openBreakpointToSide",
                                     "extra": "breakpointsFocused" },
{ "voorkant": "ctrl+enter",            "achterkant": "debug.openBreakpointToSide",
                                     "extra": "breakpointsFocused" },
{ "voorkant": "delete",                "achterkant": "debug.removeBreakpoint",
                                     "extra": "breakpointsFocused && !breakpointSelected" },
{ "voorkant": "delete",                "achterkant": "debug.removeWatchExpression",
                                     "extra": "watchExpressionsFocused && !expressionSelected" },
{ "voorkant": "shift+f9",              "achterkant": "editor.debug.action.toggleInlineBreakpoint",
                                     "extra": "editorTextFocus" },
{ "voorkant": "shift+enter",           "achterkant": "editor.refocusCallHierarchy",
                                     "extra": "callHierarchyVisible" },
{ "voorkant": "shift+alt+h",           "achterkant": "editor.showCallHierarchy",
                                     "extra": "editorHasCallHierarchyProvider && editorTextFocus && !inReferenceSearchEditor" },
{ "voorkant": "shift+alt+h",           "achterkant": "editor.toggleCallHierarchy",
                                     "extra": "callHierarchyVisible" },
{ "voorkant": "ctrl+enter",            "achterkant": "explorer.openToSide",
                                     "extra": "explorerViewletFocus && explorerViewletVisible && !inputFocus" },
{ "voorkant": "shift+alt+f",           "achterkant": "filesExplorer.findInFolder",
                                     "extra": "explorerResourceIsFolder && explorerViewletVisible && filesExplorerFocus && !inputFocus" },
{ "voorkant": "alt+down",              "achterkant": "history.showNext",
                                     "extra": "historyNavigationEnabled && historyNavigationWidget" },
{ "voorkant": "down",                  "achterkant": "history.showNext",
                                     "extra": "historyNavigationEnabled && historyNavigationWidget" },
{ "voorkant": "alt+up",                "achterkant": "history.showPrevious",
                                     "extra": "historyNavigationEnabled && historyNavigationWidget" },
{ "voorkant": "up",                    "achterkant": "history.showPrevious",
                                     "extra": "historyNavigationEnabled && historyNavigationWidget" },
{ "voorkant": "escape",                "achterkant": "keybindings.editor.clearSearchResults",
                                     "extra": "inKeybindings && inKeybindingsSearch" },
{ "voorkant": "ctrl+c",                "achterkant": "keybindings.editor.copyKeybindingEntry",
                                     "extra": "inKeybindings && keybindingFocus" },
{ "voorkant": "ctrl+k ctrl+k",         "achterkant": "keybindings.editor.defineKeybinding",
                                     "extra": "inKeybindings && keybindingFocus" },
{ "voorkant": "ctrl+k ctrl+e",         "achterkant": "keybindings.editor.defineWhenExpression",
                                     "extra": "inKeybindings && keybindingFocus" },
{ "voorkant": "down",                  "achterkant": "keybindings.editor.focusKeybindings",
                                     "extra": "inKeybindings && inKeybindingsSearch" },
{ "voorkant": "alt+k",                 "achterkant": "keybindings.editor.recordSearchKeys",
                                     "extra": "inKeybindings && inKeybindingsSearch" },
{ "voorkant": "delete",                "achterkant": "keybindings.editor.removeKeybinding",
                                     "extra": "inKeybindings && keybindingFocus" },
{ "voorkant": "ctrl+f",                "achterkant": "keybindings.editor.searchKeybindings",
                                     "extra": "inKeybindings" },
{ "voorkant": "alt+p",                 "achterkant": "keybindings.editor.toggleSortByPrecedence",
                                     "extra": "inKeybindings" },
{ "voorkant": "escape",                "achterkant": "list.clear",
                                     "extra": "listFocus && listHasSelectionOrFocus && !inputFocus" },
{ "voorkant": "left",                  "achterkant": "list.collapse",
                                     "extra": "listFocus && !inputFocus" },
{ "voorkant": "ctrl+left",             "achterkant": "list.collapseAll",
                                     "extra": "listFocus && !inputFocus" },
{ "voorkant": "right",                 "achterkant": "list.expand",
                                     "extra": "listFocus && !inputFocus" },
{ "voorkant": "shift+down",            "achterkant": "list.expandSelectionDown",
                                     "extra": "listFocus && listSupportsMultiselect && !inputFocus" },
{ "voorkant": "shift+up",              "achterkant": "list.expandSelectionUp",
                                     "extra": "listFocus && listSupportsMultiselect && !inputFocus" },
{ "voorkant": "down",                  "achterkant": "list.focusDown",
                                     "extra": "listFocus && !inputFocus" },
{ "voorkant": "home",                  "achterkant": "list.focusFirst",
                                     "extra": "listFocus && !inputFocus" },
{ "voorkant": "end",                   "achterkant": "list.focusLast",
                                     "extra": "listFocus && !inputFocus" },
{ "voorkant": "pagedown",              "achterkant": "list.focusPageDown",
                                     "extra": "listFocus && !inputFocus" },
{ "voorkant": "pageup",                "achterkant": "list.focusPageUp",
                                     "extra": "listFocus && !inputFocus" },
{ "voorkant": "up",                    "achterkant": "list.focusUp",
                                     "extra": "listFocus && !inputFocus" },
{ "voorkant": "ctrl+down",             "achterkant": "list.scrollDown",
                                     "extra": "listFocus && !inputFocus" },
{ "voorkant": "ctrl+up",               "achterkant": "list.scrollUp",
                                     "extra": "listFocus && !inputFocus" },
{ "voorkant": "enter",                 "achterkant": "list.select",
                                     "extra": "listFocus && !inputFocus" },
{ "voorkant": "ctrl+a",                "achterkant": "list.selectAll",
                                     "extra": "listFocus && listSupportsMultiselect && !inputFocus" },
{ "voorkant": "space",                 "achterkant": "list.toggleExpand",
                                     "extra": "listFocus && !inputFocus" },
{ "voorkant": "ctrl+shift+enter",      "achterkant": "list.toggleSelection",
                                     "extra": "listFocus && !inputFocus" },
{ "voorkant": "delete",                "achterkant": "notification.clear",
                                     "extra": "notificationFocus" },
{ "voorkant": "left",                  "achterkant": "notification.collapse",
                                     "extra": "notificationFocus" },
{ "voorkant": "right",                 "achterkant": "notification.expand",
                                     "extra": "notificationFocus" },
{ "voorkant": "enter",                 "achterkant": "notification.toggle",
                                     "extra": "notificationFocus" },
{ "voorkant": "space",                 "achterkant": "notification.toggle",
                                     "extra": "notificationFocus" },
{ "voorkant": "home",                  "achterkant": "notifications.focusFirstToast",
                                     "extra": "notificationFocus && notificationToastsVisible" },
{ "voorkant": "pageup",                "achterkant": "notifications.focusFirstToast",
                                     "extra": "notificationFocus && notificationToastsVisible" },
{ "voorkant": "end",                   "achterkant": "notifications.focusLastToast",
                                     "extra": "notificationFocus && notificationToastsVisible" },
{ "voorkant": "pagedown",              "achterkant": "notifications.focusLastToast",
                                     "extra": "notificationFocus && notificationToastsVisible" },
{ "voorkant": "down",                  "achterkant": "notifications.focusNextToast",
                                     "extra": "notificationFocus && notificationToastsVisible" },
{ "voorkant": "up",                    "achterkant": "notifications.focusPreviousToast",
                                     "extra": "notificationFocus && notificationToastsVisible" },
{ "voorkant": "ctrl+c",                "achterkant": "problems.action.copy",
                                     "extra": "problemFocus" },
{ "voorkant": "ctrl+f",                "achterkant": "problems.action.focusFilter",
                                     "extra": "problemsViewFocus" },
{ "voorkant": "ctrl+down",             "achterkant": "problems.action.focusProblemsFromFilter",
                                     "extra": "problemsFilterFocus" },
{ "voorkant": "ctrl+enter",            "achterkant": "problems.action.openToSide",
                                     "extra": "problemFocus" },
{ "voorkant": "ctrl+.",                "achterkant": "problems.action.showQuickFixes",
                                     "extra": "problemFocus" },
{ "voorkant": "space",                 "achterkant": "refactorPreview.toggleCheckedState",
                                     "extra": "listFocus && refactorPreview.enabled && !inputFocus" },
{ "voorkant": "shift+alt+r",           "achterkant": "revealFileInOS",
                                     "extra": "!editorFocus" },
{ "voorkant": "ctrl+enter",            "achterkant": "scm.acceptInput",
                                     "extra": "scmRepository" },
{ "voorkant": "escape",                "achterkant": "search.action.cancel",
                                     "extra": "listFocus && searchViewletVisible && !inputFocus" },
{ "voorkant": "ctrl+c",                "achterkant": "search.action.copyMatch",
                                     "extra": "fileMatchOrMatchFocus" },
{ "voorkant": "shift+alt+c",           "achterkant": "search.action.copyPath",
                                     "extra": "fileMatchOrFolderMatchWithResourceFocus" },
{ "voorkant": "f4",                    "achterkant": "search.action.focusNextSearchResult",
                                     "extra": "hasSearchResult || inSearchEditor" },
{ "voorkant": "shift+f4",              "achterkant": "search.action.focusPreviousSearchResult",
                                     "extra": "hasSearchResult || inSearchEditor" },
{ "voorkant": "ctrl+up",               "achterkant": "search.action.focusSearchFromResults",
                                     "extra": "firstMatchFocus && searchViewletVisible" },
{ "voorkant": "ctrl+enter",            "achterkant": "search.action.openResultToSide",
                                     "extra": "fileMatchOrMatchFocus && searchViewletVisible" },
{ "voorkant": "delete",                "achterkant": "search.action.remove",
                                     "extra": "fileMatchOrMatchFocus && searchViewletVisible" },
{ "voorkant": "ctrl+shift+1",          "achterkant": "search.action.replace",
                                     "extra": "matchFocus && replaceActive && searchViewletVisible" },
{ "voorkant": "ctrl+alt+enter",        "achterkant": "search.action.replaceAll",
                                     "extra": "replaceActive && searchViewletVisible && !findWidgetVisible" },
{ "voorkant": "ctrl+shift+enter",      "achterkant": "search.action.replaceAllInFile",
                                     "extra": "fileMatchFocus && replaceActive && searchViewletVisible" },
{ "voorkant": "ctrl+shift+1",          "achterkant": "search.action.replaceAllInFile",
                                     "extra": "fileMatchFocus && replaceActive && searchViewletVisible" },
{ "voorkant": "ctrl+shift+enter",      "achterkant": "search.action.replaceAllInFolder",
                                     "extra": "folderMatchFocus && replaceActive && searchViewletVisible" },
{ "voorkant": "ctrl+shift+1",          "achterkant": "search.action.replaceAllInFolder",
                                     "extra": "folderMatchFocus && replaceActive && searchViewletVisible" },
{ "voorkant": "ctrl+down",             "achterkant": "search.focus.nextInputBox",
                                     "extra": "inSearchEditor && inputBoxFocus || inputBoxFocus && searchViewletVisible" },
{ "voorkant": "ctrl+up",               "achterkant": "search.focus.previousInputBox",
                                     "extra": "inSearchEditor && inputBoxFocus || inputBoxFocus && searchViewletVisible && !searchInputBoxFocus" },
{ "voorkant": "ctrl+shift+l",          "achterkant": "selectAllSearchEditorMatches",
                                     "extra": "inSearchEditor" },
{ "voorkant": "down",                  "achterkant": "settings.action.focusSettingsFromSearch",
                                     "extra": "inSettingsSearch && !suggestWidgetVisible" },
{ "voorkant": "enter",                 "achterkant": "settings.action.focusSettingsList",
                                     "extra": "inSettingsEditor && settingsTocRowFocus" },
{ "voorkant": "shift+f9",              "achterkant": "settings.action.showContextMenu",
                                     "extra": "inSettingsEditor" },
{ "voorkant": "alt+c",                 "achterkant": "toggleSearchCaseSensitive",
                                     "extra": "searchViewletFocus && !fileMatchOrFolderMatchFocus" },
{ "voorkant": "alt+c",                 "achterkant": "toggleSearchEditorCaseSensitive",
                                     "extra": "inSearchEditor && searchInputBoxFocus" },
{ "voorkant": "alt+l",                 "achterkant": "toggleSearchEditorContextLines",
                                     "extra": "inSearchEditor" },
{ "voorkant": "alt+r",                 "achterkant": "toggleSearchEditorRegex",
                                     "extra": "inSearchEditor && searchInputBoxFocus" },
{ "voorkant": "alt+w",                 "achterkant": "toggleSearchEditorWholeWord",
                                     "extra": "inSearchEditor && searchInputBoxFocus" },
{ "voorkant": "alt+r",                 "achterkant": "toggleSearchRegex",
                                     "extra": "searchViewletFocus" },
{ "voorkant": "alt+w",                 "achterkant": "toggleSearchWholeWord",
                                     "extra": "searchViewletFocus" },
{ "voorkant": "ctrl+w",                "achterkant": "workbench.action.closeActiveEditor" },
{ "voorkant": "ctrl+f4",               "achterkant": "workbench.action.closeActiveEditor" },
{ "voorkant": "ctrl+k ctrl+w",         "achterkant": "workbench.action.closeAllEditors" },
{ "voorkant": "ctrl+k ctrl+shift+w",   "achterkant": "workbench.action.closeAllGroups" },
{ "voorkant": "ctrl+k w",              "achterkant": "workbench.action.closeEditorsInGroup" },
{ "voorkant": "ctrl+k f",              "achterkant": "workbench.action.closeFolder" },
{ "voorkant": "ctrl+w",                "achterkant": "workbench.action.closeGroup",
                                     "extra": "activeEditorGroupEmpty && multipleEditorGroups" },
{ "voorkant": "ctrl+f4",               "achterkant": "workbench.action.closeGroup",
                                     "extra": "activeEditorGroupEmpty && multipleEditorGroups" },
{ "voorkant": "shift+escape",          "achterkant": "workbench.action.closeQuickOpen",
                                     "extra": "inQuickOpen" },
{ "voorkant": "escape",                "achterkant": "workbench.action.closeQuickOpen",
                                     "extra": "inQuickOpen" },
{ "voorkant": "ctrl+k u",              "achterkant": "workbench.action.closeUnmodifiedEditors" },
{ "voorkant": "ctrl+shift+w",          "achterkant": "workbench.action.closeWindow" },
{ "voorkant": "ctrl+w",                "achterkant": "workbench.action.closeWindow",
                                     "extra": "!editorIsOpen && !multipleEditorGroups" },
{ "voorkant": "alt+f5",                "achterkant": "workbench.action.compareEditor.nextChange",
                                     "extra": "textCompareEditorVisible" },
{ "voorkant": "shift+alt+f5",          "achterkant": "workbench.action.compareEditor.previousChange",
                                     "extra": "textCompareEditorVisible" },
{ "voorkant": "f5",                    "achterkant": "workbench.action.debug.continue",
                                     "extra": "inDebugMode" },
{ "voorkant": "f6",                    "achterkant": "workbench.action.debug.pause",
                                     "extra": "debugState == 'running'" },
{ "voorkant": "ctrl+shift+f5",         "achterkant": "workbench.action.debug.restart",
                                     "extra": "inDebugMode" },
{ "voorkant": "ctrl+f5",               "achterkant": "workbench.action.debug.run" },
{ "voorkant": "f5",                    "achterkant": "workbench.action.debug.start",
                                     "extra": "!inDebugMode" },
{ "voorkant": "shift+f11",             "achterkant": "workbench.action.debug.stepOut",
                                     "extra": "debugState == 'stopped'" },
{ "voorkant": "f10",                   "achterkant": "workbench.action.debug.stepOver",
                                     "extra": "debugState == 'stopped'" },
{ "voorkant": "shift+f5",              "achterkant": "workbench.action.debug.stop",
                                     "extra": "inDebugMode" },
{ "voorkant": "ctrl+k m",              "achterkant": "workbench.action.editor.changeLanguageMode" },
{ "voorkant": "ctrl+k p",              "achterkant": "workbench.action.files.copyPathOfActiveFile" },
{ "voorkant": "ctrl+n",                "achterkant": "workbench.action.files.newUntitledFile" },
{ "voorkant": "ctrl+o",                "achterkant": "workbench.action.files.openFile" },
{ "voorkant": "ctrl+k ctrl+o",         "achterkant": "workbench.action.files.openFolder" },
{ "voorkant": "ctrl+o",                "achterkant": "workbench.action.files.openLocalFile",
                                     "extra": "remoteFileDialogVisible" },
{ "voorkant": "ctrl+k ctrl+o",         "achterkant": "workbench.action.files.openLocalFolder",
                                     "extra": "remoteFileDialogVisible" },
{ "voorkant": "ctrl+k r",              "achterkant": "workbench.action.files.revealActiveFileInWindows" },
{ "voorkant": "ctrl+s",                "achterkant": "workbench.action.files.save" },
{ "voorkant": "ctrl+k s",              "achterkant": "workbench.action.files.saveAll" },
{ "voorkant": "ctrl+shift+s",          "achterkant": "workbench.action.files.saveAs" },
{ "voorkant": "ctrl+shift+s",          "achterkant": "workbench.action.files.saveLocalFile",
                                     "extra": "remoteFileDialogVisible" },
{ "voorkant": "ctrl+k ctrl+shift+s",   "achterkant": "workbench.action.files.saveWithoutFormatting" },
{ "voorkant": "ctrl+k o",              "achterkant": "workbench.action.files.showOpenedFileInNewWindow" },
{ "voorkant": "ctrl+shift+f",          "achterkant": "workbench.action.findInFiles" },
{ "voorkant": "ctrl+k ctrl+up",        "achterkant": "workbench.action.focusAboveGroup" },
{ "voorkant": "ctrl+k ctrl+down",      "achterkant": "workbench.action.focusBelowGroup" },
{ "voorkant": "ctrl+8",                "achterkant": "workbench.action.focusEighthEditorGroup" },
{ "voorkant": "ctrl+5",                "achterkant": "workbench.action.focusFifthEditorGroup" },
{ "voorkant": "ctrl+1",                "achterkant": "workbench.action.focusFirstEditorGroup" },
{ "voorkant": "ctrl+4",                "achterkant": "workbench.action.focusFourthEditorGroup" },
{ "voorkant": "ctrl+k ctrl+left",      "achterkant": "workbench.action.focusLeftGroup" },
{ "voorkant": "ctrl+k ctrl+right",     "achterkant": "workbench.action.focusRightGroup" },
{ "voorkant": "ctrl+2",                "achterkant": "workbench.action.focusSecondEditorGroup" },
{ "voorkant": "ctrl+7",                "achterkant": "workbench.action.focusSeventhEditorGroup" },
{ "voorkant": "ctrl+0",                "achterkant": "workbench.action.focusSideBar" },
{ "voorkant": "ctrl+6",                "achterkant": "workbench.action.focusSixthEditorGroup" },
{ "voorkant": "ctrl+3",                "achterkant": "workbench.action.focusThirdEditorGroup" },
{ "voorkant": "ctrl+g",                "achterkant": "workbench.action.gotoLine" },
{ "voorkant": "ctrl+shift+o",          "achterkant": "workbench.action.gotoSymbol" },
{ "voorkant": "escape",                "achterkant": "workbench.action.hideInterfaceOverview",
                                     "extra": "interfaceOverviewVisible" },
{ "voorkant": "down",                  "achterkant": "workbench.action.interactivePlayground.arrowDown",
                                     "extra": "interactivePlaygroundFocus && !editorTextFocus" },
{ "voorkant": "up",                    "achterkant": "workbench.action.interactivePlayground.arrowUp",
                                     "extra": "interactivePlaygroundFocus && !editorTextFocus" },
{ "voorkant": "pagedown",              "achterkant": "workbench.action.interactivePlayground.pageDown",
                                     "extra": "interactivePlaygroundFocus && !editorTextFocus" },
{ "voorkant": "pageup",                "achterkant": "workbench.action.interactivePlayground.pageUp",
                                     "extra": "interactivePlaygroundFocus && !editorTextFocus" },
{ "voorkant": "ctrl+k enter",          "achterkant": "workbench.action.keepEditor" },
{ "voorkant": "ctrl+k ctrl+r",         "achterkant": "workbench.action.keybindingsReference" },
{ "voorkant": "ctrl+9",                "achterkant": "workbench.action.lastEditorInGroup" },
{ "voorkant": "alt+0",                 "achterkant": "workbench.action.lastEditorInGroup" },
{ "voorkant": "ctrl+k down",           "achterkant": "workbench.action.moveActiveEditorGroupDown" },
{ "voorkant": "ctrl+k left",           "achterkant": "workbench.action.moveActiveEditorGroupLeft" },
{ "voorkant": "ctrl+k right",          "achterkant": "workbench.action.moveActiveEditorGroupRight" },
{ "voorkant": "ctrl+k up",             "achterkant": "workbench.action.moveActiveEditorGroupUp" },
{ "voorkant": "ctrl+shift+pageup",     "achterkant": "workbench.action.moveEditorLeftInGroup" },
{ "voorkant": "ctrl+shift+pagedown",   "achterkant": "workbench.action.moveEditorRightInGroup" },
{ "voorkant": "shift+alt+1",           "achterkant": "workbench.action.moveEditorToFirstGroup" },
{ "voorkant": "shift+alt+9",           "achterkant": "workbench.action.moveEditorToLastGroup" },
{ "voorkant": "ctrl+alt+right",        "achterkant": "workbench.action.moveEditorToNextGroup" },
{ "voorkant": "ctrl+alt+left",         "achterkant": "workbench.action.moveEditorToPreviousGroup" },
{ "voorkant": "alt+left",              "achterkant": "workbench.action.navigateBack" },
{ "voorkant": "alt+right",             "achterkant": "workbench.action.navigateForward" },
{ "voorkant": "ctrl+k ctrl+q",         "achterkant": "workbench.action.navigateToLastEditLocation" },
{ "voorkant": "ctrl+shift+n",          "achterkant": "workbench.action.newWindow" },
{ "voorkant": "ctrl+pagedown",         "achterkant": "workbench.action.nextEditor" },
{ "voorkant": "ctrl+k ctrl+pagedown",  "achterkant": "workbench.action.nextEditorInGroup" },
{ "voorkant": "alt+1",                 "achterkant": "workbench.action.openEditorAtIndex1" },
{ "voorkant": "alt+2",                 "achterkant": "workbench.action.openEditorAtIndex2" },
{ "voorkant": "alt+3",                 "achterkant": "workbench.action.openEditorAtIndex3" },
{ "voorkant": "alt+4",                 "achterkant": "workbench.action.openEditorAtIndex4" },
{ "voorkant": "alt+5",                 "achterkant": "workbench.action.openEditorAtIndex5" },
{ "voorkant": "alt+6",                 "achterkant": "workbench.action.openEditorAtIndex6" },
{ "voorkant": "alt+7",                 "achterkant": "workbench.action.openEditorAtIndex7" },
{ "voorkant": "alt+8",                 "achterkant": "workbench.action.openEditorAtIndex8" },
{ "voorkant": "alt+9",                 "achterkant": "workbench.action.openEditorAtIndex9" },
{ "voorkant": "ctrl+k ctrl+s",         "achterkant": "workbench.action.openGlobalKeybindings" },
{ "voorkant": "ctrl+r",                "achterkant": "workbench.action.openRecent" },
{ "voorkant": "ctrl+,",                "achterkant": "workbench.action.openSettings" },
{ "voorkant": "ctrl+shift+u",          "achterkant": "workbench.action.output.toggleOutput" },
{ "voorkant": "ctrl+pageup",           "achterkant": "workbench.action.previousEditor" },
{ "voorkant": "ctrl+k ctrl+pageup",    "achterkant": "workbench.action.previousEditorInGroup" },
{ "voorkant": "ctrl+e",                "achterkant": "workbench.action.quickOpen" },
{ "voorkant": "ctrl+p",                "achterkant": "workbench.action.quickOpen" },
{ "voorkant": "ctrl+shift+tab",        "achterkant": "workbench.action.quickOpenLeastRecentlyUsedEditorInGroup" },
{ "voorkant": "ctrl+tab",              "achterkant": "workbench.action.quickOpenPreviousRecentlyUsedEditorInGroup" },
{ "voorkant": "ctrl+q",                "achterkant": "workbench.action.quickOpenView" },
{ "voorkant": "ctrl+shift+t",          "achterkant": "workbench.action.reopenClosedEditor" },
{ "voorkant": "ctrl+shift+h",          "achterkant": "workbench.action.replaceInFiles" },
{ "voorkant": "ctrl+shift+j",          "achterkant": "workbench.action.search.toggleQueryDetails",
                                     "extra": "inSearchEditor || searchViewletFocus" },
{ "voorkant": "ctrl+k ctrl+t",         "achterkant": "workbench.action.selectTheme" },
{ "voorkant": "ctrl+k ctrl+p",         "achterkant": "workbench.action.showAllEditors" },
{ "voorkant": "ctrl+t",                "achterkant": "workbench.action.showAllSymbols" },
{ "voorkant": "f1",                    "achterkant": "workbench.action.showCommands" },
{ "voorkant": "ctrl+shift+p",          "achterkant": "workbench.action.showCommands" },
{ "voorkant": "ctrl+\\",               "achterkant": "workbench.action.splitEditor" },
{ "voorkant": "ctrl+k ctrl+\\",        "achterkant": "workbench.action.splitEditorOrthogonal" },
{ "voorkant": "ctrl+shift+b",          "achterkant": "workbench.action.tasks.build" },
{ "voorkant": "escape",                "achterkant": "workbench.action.terminal.clearSelection",
                                     "extra": "terminalFocus && terminalTextSelected && !terminalFindWidgetVisible" },
{ "voorkant": "ctrl+shift+c",          "achterkant": "workbench.action.terminal.copySelection",
                                     "extra": "terminalFocus && terminalTextSelected" },
{ "voorkant": "ctrl+c",                "achterkant": "workbench.action.terminal.copySelection",
                                     "extra": "terminalFocus && terminalTextSelected" },
{ "voorkant": "ctrl+backspace",        "achterkant": "workbench.action.terminal.deleteWordLeft",
                                     "extra": "terminalFocus" },
{ "voorkant": "ctrl+delete",           "achterkant": "workbench.action.terminal.deleteWordRight",
                                     "extra": "terminalFocus" },
{ "voorkant": "shift+enter",           "achterkant": "workbench.action.terminal.findNext",
                                     "extra": "terminalFindWidgetFocused" },
{ "voorkant": "f3",                    "achterkant": "workbench.action.terminal.findNext",
                                     "extra": "terminalFocus" },
{ "voorkant": "f3",                    "achterkant": "workbench.action.terminal.findNext",
                                     "extra": "terminalFindWidgetFocused" },
{ "voorkant": "enter",                 "achterkant": "workbench.action.terminal.findPrevious",
                                     "extra": "terminalFindWidgetFocused" },
{ "voorkant": "shift+f3",              "achterkant": "workbench.action.terminal.findPrevious",
                                     "extra": "terminalFocus" },
{ "voorkant": "shift+f3",              "achterkant": "workbench.action.terminal.findPrevious",
                                     "extra": "terminalFindWidgetFocused" },
{ "voorkant": "ctrl+f",                "achterkant": "workbench.action.terminal.focusFindWidget",
                                     "extra": "terminalFocus" },
{ "voorkant": "ctrl+f",                "achterkant": "workbench.action.terminal.focusFindWidget",
                                     "extra": "terminalFindWidgetFocused" },
{ "voorkant": "alt+down",              "achterkant": "workbench.action.terminal.focusNextPane",
                                     "extra": "terminalFocus" },
{ "voorkant": "alt+right",             "achterkant": "workbench.action.terminal.focusNextPane",
                                     "extra": "terminalFocus" },
{ "voorkant": "alt+up",                "achterkant": "workbench.action.terminal.focusPreviousPane",
                                     "extra": "terminalFocus" },
{ "voorkant": "alt+left",              "achterkant": "workbench.action.terminal.focusPreviousPane",
                                     "extra": "terminalFocus" },
{ "voorkant": "shift+escape",          "achterkant": "workbench.action.terminal.hideFindWidget",
                                     "extra": "terminalFindWidgetVisible && terminalFocus" },
{ "voorkant": "escape",                "achterkant": "workbench.action.terminal.hideFindWidget",
                                     "extra": "terminalFindWidgetVisible && terminalFocus" },
{ "voorkant": "escape",                "achterkant": "workbench.action.terminal.navigationModeExit",
                                     "extra": "accessibilityModeEnabled && terminalA11yTreeFocus" },
{ "voorkant": "ctrl+down",             "achterkant": "workbench.action.terminal.navigationModeFocusNext",
                                     "extra": "accessibilityModeEnabled && terminalFocus" },
{ "voorkant": "ctrl+down",             "achterkant": "workbench.action.terminal.navigationModeFocusNext",
                                     "extra": "accessibilityModeEnabled && terminalA11yTreeFocus" },
{ "voorkant": "ctrl+up",               "achterkant": "workbench.action.terminal.navigationModeFocusPrevious",
                                     "extra": "accessibilityModeEnabled && terminalFocus" },
{ "voorkant": "ctrl+up",               "achterkant": "workbench.action.terminal.navigationModeFocusPrevious",
                                     "extra": "accessibilityModeEnabled && terminalA11yTreeFocus" },
{ "voorkant": "ctrl+shift+`",          "achterkant": "workbench.action.terminal.new" },
{ "voorkant": "ctrl+shift+c",          "achterkant": "workbench.action.terminal.openNativeConsole",
                                     "extra": "!terminalFocus" },
{ "voorkant": "ctrl+shift+v",          "achterkant": "workbench.action.terminal.paste",
                                     "extra": "terminalFocus" },
{ "voorkant": "ctrl+v",                "achterkant": "workbench.action.terminal.paste",
                                     "extra": "terminalFocus" },
{ "voorkant": "ctrl+alt+pagedown",     "achterkant": "workbench.action.terminal.scrollDown",
                                     "extra": "terminalFocus" },
{ "voorkant": "shift+pagedown",        "achterkant": "workbench.action.terminal.scrollDownPage",
                                     "extra": "terminalFocus" },
{ "voorkant": "ctrl+end",              "achterkant": "workbench.action.terminal.scrollToBottom",
                                     "extra": "terminalFocus" },
{ "voorkant": "ctrl+home",             "achterkant": "workbench.action.terminal.scrollToTop",
                                     "extra": "terminalFocus" },
{ "voorkant": "ctrl+alt+pageup",       "achterkant": "workbench.action.terminal.scrollUp",
                                     "extra": "terminalFocus" },
{ "voorkant": "shift+pageup",          "achterkant": "workbench.action.terminal.scrollUpPage",
                                     "extra": "terminalFocus" },
{ "voorkant": "ctrl+shift+5",          "achterkant": "workbench.action.terminal.split",
                                     "extra": "terminalFocus" },
{ "voorkant": "alt+c",                 "achterkant": "workbench.action.terminal.toggleFindCaseSensitive",
                                     "extra": "terminalFindWidgetFocused" },
{ "voorkant": "alt+c",                 "achterkant": "workbench.action.terminal.toggleFindCaseSensitive",
                                     "extra": "terminalFocus" },
{ "voorkant": "alt+r",                 "achterkant": "workbench.action.terminal.toggleFindRegex",
                                     "extra": "terminalFindWidgetFocused" },
{ "voorkant": "alt+r",                 "achterkant": "workbench.action.terminal.toggleFindRegex",
                                     "extra": "terminalFocus" },
{ "voorkant": "alt+w",                 "achterkant": "workbench.action.terminal.toggleFindWholeWord",
                                     "extra": "terminalFindWidgetFocused" },
{ "voorkant": "alt+w",                 "achterkant": "workbench.action.terminal.toggleFindWholeWord",
                                     "extra": "terminalFocus" },
{ "voorkant": "ctrl+`",                "achterkant": "workbench.action.terminal.toggleTerminal" },
{ "voorkant": "shift+alt+0",           "achterkant": "workbench.action.toggleEditorGroupLayout" },
{ "voorkant": "f11",                   "achterkant": "workbench.action.toggleFullScreen" },
{ "voorkant": "ctrl+j",                "achterkant": "workbench.action.togglePanel" },
{ "voorkant": "ctrl+b",                "achterkant": "workbench.action.toggleSidebarVisibility" },
{ "voorkant": "ctrl+k z",              "achterkant": "workbench.action.toggleZenMode" },
{ "voorkant": "ctrl+numpad_add",       "achterkant": "workbench.action.zoomIn" },
{ "voorkant": "ctrl+shift+=",          "achterkant": "workbench.action.zoomIn" },
{ "voorkant": "ctrl+=",                "achterkant": "workbench.action.zoomIn" },
{ "voorkant": "ctrl+numpad_subtract",  "achterkant": "workbench.action.zoomOut" },
{ "voorkant": "ctrl+shift+-",          "achterkant": "workbench.action.zoomOut" },
{ "voorkant": "ctrl+-",                "achterkant": "workbench.action.zoomOut" },
{ "voorkant": "ctrl+numpad0",          "achterkant": "workbench.action.zoomReset" },
{ "voorkant": "ctrl+shift+m",          "achterkant": "workbench.actions.view.problems" },
{ "voorkant": "ctrl+shift+y",          "achterkant": "workbench.debug.action.toggleRepl" },
{ "voorkant": "ctrl+k ctrl+m",         "achterkant": "workbench.extensions.action.showRecommendedKeymapExtensions" },
{ "voorkant": "ctrl+k c",              "achterkant": "workbench.files.action.compareWithClipboard" },
{ "voorkant": "ctrl+k d",              "achterkant": "workbench.files.action.compareWithSaved" },
{ "voorkant": "ctrl+k e",              "achterkant": "workbench.files.action.focusOpenEditorsView",
                                     "extra": "workbench.explorer.openEditorsView.active" },
{ "voorkant": "ctrl+shift+d",          "achterkant": "workbench.view.debug" },
{ "voorkant": "ctrl+shift+e",          "achterkant": "workbench.view.explorer" },
{ "voorkant": "ctrl+shift+x",          "achterkant": "workbench.view.extensions" },
{ "voorkant": "ctrl+shift+g",          "achterkant": "workbench.view.scm" },
{ "voorkant": "ctrl+shift+f",          "achterkant": "workbench.view.search",
                                     "extra": "!searchViewletVisible" },
{ "voorkant": "ctrl+right",            "achterkant": "breadcrumbs.focusNextWithPicker",
                                     "extra": "breadcrumbsActive && breadcrumbsVisible && listFocus && !inputFocus" },
{ "voorkant": "ctrl+left",             "achterkant": "breadcrumbs.focusPreviousWithPicker",
                                     "extra": "breadcrumbsActive && breadcrumbsVisible && listFocus && !inputFocus" },
{ "voorkant": "escape",                "achterkant": "breadcrumbs.selectEditor",
                                     "extra": "breadcrumbsActive && breadcrumbsVisible" },
{ "voorkant": "f2",                    "achterkant": "debug.renameWatchExpression",
                                     "extra": "watchExpressionsFocused" },
{ "voorkant": "f2",                    "achterkant": "debug.setVariable",
                                     "extra": "variablesFocused" },
{ "voorkant": "space",                 "achterkant": "debug.toggleBreakpoint",
                                     "extra": "breakpointsFocused && !inputFocus" },
{ "voorkant": "shift+delete",          "achterkant": "deleteFile",
                                     "extra": "explorerViewletVisible && filesExplorerFocus && !explorerResourceReadonly && !inputFocus" },
{ "voorkant": "delete",                "achterkant": "deleteFile",
                                     "extra": "explorerViewletVisible && filesExplorerFocus && !explorerResourceMoveableToTrash && !explorerResourceReadonly && !inputFocus" },
{ "voorkant": "escape",                "achterkant": "editor.closeCallHierarchy",
                                     "extra": "callHierarchyVisible && !config.editor.stablePeek" },
{ "voorkant": "escape",                "achterkant": "filesExplorer.cancelCut",
                                     "extra": "explorerResourceCut && explorerViewletVisible && filesExplorerFocus && !inputFocus" },
{ "voorkant": "ctrl+c",                "achterkant": "filesExplorer.copy",
                                     "extra": "explorerViewletVisible && filesExplorerFocus && !explorerResourceIsRoot && !inputFocus" },
{ "voorkant": "ctrl+x",                "achterkant": "filesExplorer.cut",
                                     "extra": "explorerViewletVisible && filesExplorerFocus && !explorerResourceIsRoot && !inputFocus" },
{ "voorkant": "space",                 "achterkant": "filesExplorer.openFilePreserveFocus",
                                     "extra": "explorerViewletVisible && filesExplorerFocus && !explorerResourceIsFolder && !inputFocus" },
{ "voorkant": "ctrl+v",                "achterkant": "filesExplorer.paste",
                                     "extra": "explorerViewletVisible && filesExplorerFocus && !explorerResourceReadonly && !inputFocus" },
{ "voorkant": "home",                  "achterkant": "firstCompressedFolder",
                                     "extra": "explorerViewletCompressedFocus && explorerViewletVisible && filesExplorerFocus && !explorerViewletCompressedFirstFocus && !inputFocus" },
{ "voorkant": "end",                   "achterkant": "lastCompressedFolder",
                                     "extra": "explorerViewletCompressedFocus && explorerViewletVisible && filesExplorerFocus && !explorerViewletCompressedLastFocus && !inputFocus" },
{ "voorkant": "delete",                "achterkant": "moveFileToTrash",
                                     "extra": "explorerResourceMoveableToTrash && explorerViewletVisible && filesExplorerFocus && !explorerResourceReadonly && !inputFocus" },
{ "voorkant": "right",                 "achterkant": "nextCompressedFolder",
                                     "extra": "explorerViewletCompressedFocus && explorerViewletVisible && filesExplorerFocus && !explorerViewletCompressedLastFocus && !inputFocus" },
{ "voorkant": "left",                  "achterkant": "previousCompressedFolder",
                                     "extra": "explorerViewletCompressedFocus && explorerViewletVisible && filesExplorerFocus && !explorerViewletCompressedFirstFocus && !inputFocus" },
{ "voorkant": "delete",                "achterkant": "remote.tunnel.closeInline",
                                     "extra": "tunnelCloseable && tunnelViewFocus" },
{ "voorkant": "ctrl+c",                "achterkant": "remote.tunnel.copyAddressInline",
                                     "extra": "tunnelViewFocus && tunnelType == 'Detected' || tunnelViewFocus && tunnelType == 'Forwarded'" },
{ "voorkant": "f2",                    "achterkant": "remote.tunnel.label",
                                     "extra": "tunnelViewFocus && tunnelType == 'Forwarded'" },
{ "voorkant": "f2",                    "achterkant": "renameFile",
                                     "extra": "explorerViewletVisible && filesExplorerFocus && !explorerResourceIsRoot && !explorerResourceReadonly && !inputFocus" },
{ "voorkant": "f11",                   "achterkant": "workbench.action.debug.stepInto",
                                     "extra": "debugState != 'inactive'" },
{ "voorkant": "shift+escape",          "achterkant": "closeReferenceSearch",
                                     "extra": "referenceSearchVisible && !config.editor.stablePeek" },
{ "voorkant": "escape",                "achterkant": "closeReferenceSearch",
                                     "extra": "referenceSearchVisible && !config.editor.stablePeek" },
{ "voorkant": "escape",                "achterkant": "notifications.hideList",
                                     "extra": "notificationCenterVisible" },
{ "voorkant": "escape",                "achterkant": "notifications.hideToasts",
                                     "extra": "notificationToastsVisible" },
{ "voorkant": "alt+left",              "achterkant": "workbench.action.quickInputBack",
                                     "extra": "inQuickOpen" },
{ "voorkant": "ctrl+tab",              "achterkant": "workbench.action.quickOpenNavigateNextInEditorPicker",
                                     "extra": "inEditorsPicker && inQuickOpen" },
{ "voorkant": "ctrl+e",                "achterkant": "workbench.action.quickOpenNavigateNextInFilePicker",
                                     "extra": "inFilesPicker && inQuickOpen" },
{ "voorkant": "ctrl+p",                "achterkant": "workbench.action.quickOpenNavigateNextInFilePicker",
                                     "extra": "inFilesPicker && inQuickOpen" },
{ "voorkant": "ctrl+r",                "achterkant": "workbench.action.quickOpenNavigateNextInRecentFilesPicker",
                                     "extra": "inQuickOpen && inRecentFilesPicker" },
{ "voorkant": "ctrl+q",                "achterkant": "workbench.action.quickOpenNavigateNextInViewPicker",
                                     "extra": "inQuickOpen && inViewsPicker" },
{ "voorkant": "ctrl+shift+tab",        "achterkant": "workbench.action.quickOpenNavigatePreviousInEditorPicker",
                                     "extra": "inEditorsPicker && inQuickOpen" },
{ "voorkant": "ctrl+shift+e",          "achterkant": "workbench.action.quickOpenNavigatePreviousInFilePicker",
                                     "extra": "inFilesPicker && inQuickOpen" },
{ "voorkant": "ctrl+shift+p",          "achterkant": "workbench.action.quickOpenNavigatePreviousInFilePicker",
                                     "extra": "inFilesPicker && inQuickOpen" },
{ "voorkant": "ctrl+shift+r",          "achterkant": "workbench.action.quickOpenNavigatePreviousInRecentFilesPicker",
                                     "extra": "inQuickOpen && inRecentFilesPicker" },
{ "voorkant": "ctrl+shift+q",          "achterkant": "workbench.action.quickOpenNavigatePreviousInViewPicker",
                                     "extra": "inQuickOpen && inViewsPicker" },
{ "voorkant": "ctrl+r",                "achterkant": "workbench.action.reloadWindow",
                                     "extra": "isDevelopment" },
{ "voorkant": "ctrl+shift+i",          "achterkant": "workbench.action.toggleDevTools",
                                     "extra": "isDevelopment" },
{ "voorkant": "ctrl+f4",               "achterkant": "extension.node-debug.pickLoadedScript",
                                     "extra": "debugType == 'node2'" },
{ "voorkant": "f10",                   "achterkant": "extension.node-debug.startWithStopOnEntry",
                                     "extra": "!inDebugMode && debugConfigurationType == 'node'" },
{ "voorkant": "ctrl+shift+v",          "achterkant": "markdown.showPreview",
                                     "extra": "editorLangId == 'markdown'" },
{ "voorkant": "shift+alt+f12",         "achterkant": "references-view.find",
                                     "extra": "editorHasReferenceProvider" },
{ "voorkant": "ctrl+k v",              "achterkant": "markdown.showPreviewToSide",
                                     "extra": "editorLangId == 'markdown'" },
{ "voorkant": "f4",                    "achterkant": "references-view.next",
                                     "extra": "reference-list.hasResult" },
{ "voorkant": "shift+f4",              "achterkant": "references-view.prev",
                                     "extra": "reference-list.hasResult" },
{ "voorkant": "shift+alt+h",           "achterkant": "references-view.showCallHierarchy",
                                     "extra": "editorHasCallHierarchyProvider" },
{ "voorkant": "ctrl+f1",               "achterkant": "PowerShell.ShowHelp",
                                     "extra": "editorTextFocus && editorLangId == 'powershell'" },
{ "voorkant": "f4",                    "achterkant": "dart.showTypeHierarchy",
                                     "extra": "editorLangId == 'dart'" },
{ "voorkant": "escape",                "achterkant": "metaGo.input.cancel",
                                     "extra": "editorTextFocus && metaGoInput" },
{ "voorkant": "shift+alt+e",           "achterkant": "PowerShell.ExpandAlias",
                                     "extra": "editorTextFocus && editorLangId == 'powershell'" },
{ "voorkant": "ctrl+f5",               "achterkant": "flutter.hotReload",
                                     "extra": "dart-code:anyFlutterProjectLoaded && dart-code:service.reloadSources && inDebugMode" },
{ "voorkant": "backspace",             "achterkant": "metaGo.metaJump.backspace",
                                     "extra": "editorTextFocus && metaGoJumping" },
{ "voorkant": "shift+alt+s",           "achterkant": "PowerShell.ShowAdditionalCommands",
                                     "extra": "editorTextFocus && editorLangId == 'powershell'" },
{ "voorkant": "ctrl+shift+f5",         "achterkant": "dart.rerunLastDebugSession",
                                     "extra": "dart-code:dartProjectLoaded && dart-code:hasLastDebugConfig && !inDebugMode" },
{ "voorkant": "alt+,",                 "achterkant": "metaGo.gotoBefore" },
{ "voorkant": "f8",                    "achterkant": "PowerShell.RunSelection",
                                     "extra": "editorTextFocus && editorLangId == 'powershell'" },
{ "voorkant": "ctrl+alt+d",            "achterkant": "dart.openDevTools",
                                     "extra": "dart-code:dartProjectLoaded" },
{ "voorkant": "alt+.",                 "achterkant": "metaGo.gotoAfter" },
{ "voorkant": "ctrl+alt+j",            "achterkant": "editor.action.insertSnippet",
                                     "extra": "editorTextFocus && editorLangId == 'powershell'" },
{ "voorkant": "alt+/",                 "achterkant": "metaGo.gotoSmart" },
{ "voorkant": "shift+alt+,",           "achterkant": "metaGo.selectBefore",
                                     "extra": "editorTextFocus" },
{ "voorkant": "shift+alt+.",           "achterkant": "metaGo.selectAfter",
                                     "extra": "editorTextFocus" },
{ "voorkant": "shift+alt+/",           "achterkant": "metaGo.selectSmart",
                                     "extra": "editorTextFocus" },
{ "voorkant": "ctrl+shift+l",          "achterkant": "metaGo.selectLineUp",
                                     "extra": "editorTextFocus" },
{ "voorkant": "ctrl+l",                "achterkant": "metaGo.selectLineDown",
                                     "extra": "editorTextFocus" },
{ "voorkant": "alt+m",                 "achterkant": "metaGo.scrollCurrentLineToMiddle",
                                     "extra": "editorTextFocus" },
{ "voorkant": "alt+b",                 "achterkant": "metaGo.scrollCurrentLineToBottom",
                                     "extra": "editorTextFocus" },
{ "voorkant": "alt+t",                 "achterkant": "metaGo.scrollCurrentLineToTop",
                                     "extra": "editorTextFocus" },
{ "voorkant": "alt+home",              "achterkant": "metaGo.gotoEmptyLineUp",
                                     "extra": "editorTextFocus" },
{ "voorkant": "shift+alt+home",        "achterkant": "metaGo.selectEmptyLineUp",
                                     "extra": "editorTextFocus" },
{ "voorkant": "alt+end",               "achterkant": "metaGo.gotoEmptyLineDown",
                                     "extra": "editorTextFocus" },
{ "voorkant": "shift+alt+end",         "achterkant": "metaGo.selectEmptyLineDown",
                                     "extra": "editorTextFocus" },
{ "voorkant": "alt+'",                 "achterkant": "metaGo.bookmark.toggle",
                                     "extra": "editorTextFocus" },
{ "voorkant": "alt+\\",                "achterkant": "metaGo.bookmark.view",
                                     "extra": "editorTextFocus" },
{ "voorkant": "alt+[",                 "achterkant": "metaGo.bookmark.previous",
                                     "extra": "editorTextFocus" },
{ "voorkant": "alt+]",                 "achterkant": "metaGo.bookmark.next",
                                     "extra": "editorTextFocus" },
{ "voorkant": "ctrl+shift+\\",         "achterkant": "metaGo.jumpToBracket",
                                     "extra": "editorTextFocus" }
]
}
  ''';
