var vscodesettins = '''[{"book": {
    "title": "vscode keyboard",
    "description": "Algemeen"
  },
"page":[{"voorkant":"Ctrl+X","achterkant":"Cut line (empty selection)","extra":"editor.action.clipboardCutAction"},
{"voorkant":"Ctrl+C","achterkant":"Copy line (empty selection)","extra":"editor.action.clipboardCopyAction"},
{"voorkant":"Ctrl+V","achterkant":"Paste","extra":"editor.action.clipboardPasteAction"},
{"voorkant":"Ctrl+Shift+K","achterkant":"Delete Line","extra":"editor.action.deleteLines"},
{"voorkant":"Ctrl+Enter","achterkant":"Insert Line Below","extra":"editor.action.insertLineAfter"},
{"voorkant":"Ctrl+Shift+Enter","achterkant":"Insert Line Above","extra":"editor.action.insertLineBefore"},
{"voorkant":"Alt+Down","achterkant":"Move Line Down","extra":"editor.action.moveLinesDownAction"},
{"voorkant":"Alt+Up","achterkant":"Move Line Up","extra":"editor.action.moveLinesUpAction"},
{"voorkant":"Shift+Alt+Down","achterkant":"Copy Line Down","extra":"editor.action.copyLinesDownAction"},
{"voorkant":"Shift+Alt+Up","achterkant":"Copy Line Up","extra":"editor.action.copyLinesUpAction"},
{"voorkant":"Ctrl+Z","achterkant":"Undo","extra":"undo"},
{"voorkant":"Ctrl+Y","achterkant":"Redo","extra":"redo"},
{"voorkant":"Ctrl+D","achterkant":"Add Selection To Next Find Match","extra":"editor.action.addSelectionToNextFindMatch"},
{"voorkant":"Ctrl+K Ctrl+D","achterkant":"Move Last Selection To Next Find Match","extra":"editor.action.moveSelectionToNextFindMatch"},
{"voorkant":"Ctrl+U","achterkant":"Undo last cursor operation","extra":"cursorUndo"},
{"voorkant":"Shift+Alt+I","achterkant":"Insert cursor at end of each line selected","extra":"editor.action.insertCursorAtEndOfEachLineSelected"},
{"voorkant":"Ctrl+Shift+L","achterkant":"Select all occurrences of current selection","extra":"editor.action.selectHighlights"},
{"voorkant":"Ctrl+F2","achterkant":"Select all occurrences of current word","extra":"editor.action.changeAll"},
{"voorkant":"Ctrl+L","achterkant":"Select current line","extra":"expandLineSelection"},
{"voorkant":"Ctrl+Alt+Down","achterkant":"Insert Cursor Below","extra":"editor.action.insertCursorBelow"},
{"voorkant":"Ctrl+Alt+Up","achterkant":"Insert Cursor Above","extra":"editor.action.insertCursorAbove"},
{"voorkant":"Ctrl+Shift+\\","achterkant":"Jump to matching bracket","extra":"editor.action.jumpToBracket"},
{"voorkant":"Ctrl+]","achterkant":"Indent Line","extra":"editor.action.indentLines"},
{"voorkant":"Ctrl+[","achterkant":"Outdent Line","extra":"editor.action.outdentLines"},
{"voorkant":"Home","achterkant":"Go to Beginning of Line","extra":"cursorHome"},
{"voorkant":"End","achterkant":"Go to End of Line","extra":"cursorEnd"},
{"voorkant":"Ctrl+End","achterkant":"Go to End of File","extra":"cursorBottom"},
{"voorkant":"Ctrl+Home","achterkant":"Go to Beginning of File","extra":"cursorTop"},
{"voorkant":"Ctrl+Down","achterkant":"Scroll Line Down","extra":"scrollLineDown"},
{"voorkant":"Ctrl+Up","achterkant":"Scroll Line Up","extra":"scrollLineUp"},
{"voorkant":"Alt+PageDown","achterkant":"Scroll Page Down","extra":"scrollPageDown"},
{"voorkant":"Alt+PageUp","achterkant":"Scroll Page Up","extra":"scrollPageUp"},
{"voorkant":"Ctrl+Shift+[","achterkant":"Fold (collapse) region","extra":"editor.fold"},
{"voorkant":"Ctrl+Shift+]","achterkant":"Unfold (uncollapse) region","extra":"editor.unfold"},
{"voorkant":"Ctrl+K Ctrl+[","achterkant":"Fold (collapse) all subregions","extra":"editor.foldRecursively"},
{"voorkant":"Ctrl+K Ctrl+]","achterkant":"Unfold (uncollapse) all subregions","extra":"editor.unfoldRecursively"},
{"voorkant":"Ctrl+K Ctrl+0","achterkant":"Fold (collapse) all regions","extra":"editor.foldAll"},
{"voorkant":"Ctrl+K Ctrl+J","achterkant":"Unfold (uncollapse) all regions","extra":"editor.unfoldAll"},
{"voorkant":"Ctrl+K Ctrl+C","achterkant":"Add Line Comment","extra":"editor.action.addCommentLine"},
{"voorkant":"Ctrl+K Ctrl+U","achterkant":"Remove Line Comment","extra":"editor.action.removeCommentLine"},
{"voorkant":"Ctrl+/","achterkant":"Toggle Line Comment","extra":"editor.action.commentLine"},
{"voorkant":"Shift+Alt+A","achterkant":"Toggle Block Comment","extra":"editor.action.blockComment"},
{"voorkant":"Ctrl+F","achterkant":"Find","extra":"actions.find"},
{"voorkant":"Ctrl+H","achterkant":"Replace","extra":"editor.action.startFindReplaceAction"},
{"voorkant":"Enter","achterkant":"Find Next","extra":"editor.action.nextMatchFindAction"},
{"voorkant":"Shift+Enter","achterkant":"Find Previous","extra":"editor.action.previousMatchFindAction"},
{"voorkant":"Alt+Enter","achterkant":"Select All Occurrences of Find Match","extra":"editor.action.selectAllMatches"},
{"voorkant":"Alt+C","achterkant":"Toggle Find Case Sensitive","extra":"toggleFindCaseSensitive"},
{"voorkant":"Alt+R","achterkant":"Toggle Find Regex","extra":"toggleFindRegex"},
{"voorkant":"Alt+W","achterkant":"Toggle Find Whole Word","extra":"toggleFindWholeWord"},
{"voorkant":"Ctrl+M","achterkant":"Toggle Use of Tab Key for Setting Focus","extra":"editor.action.toggleTabFocusMode"},
{"voorkant":"unassigned","achterkant":"Toggle Render Whitespace","extra":"toggleRenderWhitespace"},
{"voorkant":"Alt+Z","achterkant":"Toggle Word Wrap","extra":"editor.action.toggleWordWrap"}
]
},
{"book": {
    "title": "vscode keyboard",
    "description": "Rich Languages Editing"
  },
"page":[{"voorkant":"Key","achterkant":"Command","extra":"Command id"},
{"voorkant":"Ctrl+Space","achterkant":"Trigger Suggest","extra":"editor.action.triggerSuggest"},
{"voorkant":"Ctrl+Shift+Space","achterkant":"Trigger Parameter Hints","extra":"editor.action.triggerParameterHints"},
{"voorkant":"Shift+Alt+F","achterkant":"Format Document","extra":"editor.action.formatDocument"},
{"voorkant":"Ctrl+K Ctrl+F","achterkant":"Format Selection","extra":"editor.action.formatSelection"},
{"voorkant":"F12","achterkant":"Go to Definition","extra":"editor.action.revealDefinition"},
{"voorkant":"Ctrl+K Ctrl+I","achterkant":"Show Hover","extra":"editor.action.showHover"},
{"voorkant":"Alt+F12","achterkant":"Peek Definition","extra":"editor.action.peekDefinition"},
{"voorkant":"Ctrl+K F12","achterkant":"Open Definition to the Side","extra":"editor.action.revealDefinitionAside"},
{"voorkant":"Ctrl+.","achterkant":"Quick Fix","extra":"editor.action.quickFix"},
{"voorkant":"Shift+F12","achterkant":"Go to References","extra":"editor.action.goToReferences"},
{"voorkant":"F2","achterkant":"Rename Symbol","extra":"editor.action.rename"},
{"voorkant":"Ctrl+Shift+.","achterkant":"Replace with Next Value","extra":"editor.action.inPlaceReplace.down"},
{"voorkant":"Ctrl+Shift+,","achterkant":"Replace with Previous Value","extra":"editor.action.inPlaceReplace.up"},
{"voorkant":"Shift+Alt+Right","achterkant":"Expand AST Selection","extra":"editor.action.smartSelect.expand"},
{"voorkant":"Shift+Alt+Left","achterkant":"Shrink AST Selection","extra":"editor.action.smartSelect.shrink"},
{"voorkant":"Ctrl+K Ctrl+X","achterkant":"Trim Trailing Whitespace","extra":"editor.action.trimTrailingWhitespace"},
{"voorkant":"Ctrl+K M","achterkant":"Change Language Mode","extra":"workbench.action.editor.changeLanguageMode"}
]
},
{"book": {
    "title": "vscode keyboard",
    "description": "Navigation"
  },
"page":[{"voorkant":"Key","achterkant":"Command","extra":"Command id"},
{"voorkant":"Ctrl+T","achterkant":"Show All Symbols","extra":"workbench.action.showAllSymbols"},
{"voorkant":"Ctrl+G","achterkant":"Go to Line...","extra":"workbench.action.gotoLine"},
{"voorkant":"Ctrl+P","achterkant":"Go to File..., Quick Open","extra":"workbench.action.quickOpen"},
{"voorkant":"Ctrl+Shift+O","achterkant":"Go to Symbol...","extra":"workbench.action.gotoSymbol"},
{"voorkant":"Ctrl+Shift+M","achterkant":"Show Problems","extra":"workbench.actions.view.problems"},
{"voorkant":"F8","achterkant":"Go to Next Error or Warning","extra":"editor.action.marker.nextInFiles"},
{"voorkant":"Shift+F8","achterkant":"Go to Previous Error or Warning","extra":"editor.action.marker.prevInFiles"},
{"voorkant":"Ctrl+Shift+P or F1","achterkant":"Show All Commands","extra":"workbench.action.showCommands"},
{"voorkant":"Ctrl+Tab","achterkant":"Navigate Editor Group History","extra":"workbench.action.quickOpenPreviousRecentlyUsedEditorInGroup"},
{"voorkant":"Alt+Left","achterkant":"Go Back","extra":"workbench.action.navigateBack"},
{"voorkant":"Alt+Left","achterkant":"Go back in Quick Input","extra":"workbench.action.quickInputBack"},
{"voorkant":"Alt+Right","achterkant":"Go Forward","extra":"workbench.action.navigateForward"}
]
},
{"book": {
    "title": "vscode keyboard",
    "description": "Editor/Window Management"
  },
"page":[{"voorkant":"Key","achterkant":"Command","extra":"Command id"},
{"voorkant":"Ctrl+Shift+N","achterkant":"New Window","extra":"workbench.action.newWindow"},
{"voorkant":"Ctrl+W","achterkant":"Close Window","extra":"workbench.action.closeWindow"},
{"voorkant":"Ctrl+F4","achterkant":"Close Editor","extra":"workbench.action.closeActiveEditor"},
{"voorkant":"Ctrl+K F","achterkant":"Close Folder","extra":"workbench.action.closeFolder"},
{"voorkant":"unassigned","achterkant":"Cycle Between Editor Groups","extra":"workbench.action.navigateEditorGroups"},
{"voorkant":"Ctrl+\\","achterkant":"Split Editor","extra":"workbench.action.splitEditor"},
{"voorkant":"Ctrl+1","achterkant":"Focus into First Editor Group","extra":"workbench.action.focusFirstEditorGroup"},
{"voorkant":"Ctrl+2","achterkant":"Focus into Second Editor Group","extra":"workbench.action.focusSecondEditorGroup"},
{"voorkant":"Ctrl+3","achterkant":"Focus into Third Editor Group","extra":"workbench.action.focusThirdEditorGroup"},
{"voorkant":"unassigned","achterkant":"Focus into Editor Group on the Left","extra":"workbench.action.focusPreviousGroup"},
{"voorkant":"unassigned","achterkant":"Focus into Editor Group on the Right","extra":"workbench.action.focusNextGroup"},
{"voorkant":"Ctrl+Shift+PageUp","achterkant":"Move Editor Left","extra":"workbench.action.moveEditorLeftInGroup"},
{"voorkant":"Ctrl+Shift+PageDown","achterkant":"Move Editor Right","extra":"workbench.action.moveEditorRightInGroup"},
{"voorkant":"Ctrl+K Left","achterkant":"Move Active Editor Group Left","extra":"workbench.action.moveActiveEditorGroupLeft"},
{"voorkant":"Ctrl+K Right","achterkant":"Move Active Editor Group Right","extra":"workbench.action.moveActiveEditorGroupRight"},
{"voorkant":"Ctrl+Alt+Right","achterkant":"Move Editor into Next Group","extra":"workbench.action.moveEditorToNextGroup"},
{"voorkant":"Ctrl+Alt+Left","achterkant":"Move Editor into Previous Group","extra":"workbench.action.moveEditorToPreviousGroup"}
]
},
{"book": {
    "title": "vscode keyboard",
    "description": "File Management"
  },
"page":[{"voorkant":"Key","achterkant":"Command","extra":"Command id"},
{"voorkant":"Ctrl+N","achterkant":"New File","extra":"workbench.action.files.newUntitledFile"},
{"voorkant":"Ctrl+O","achterkant":"Open File...","extra":"workbench.action.files.openFile"},
{"voorkant":"Ctrl+S","achterkant":"Save","extra":"workbench.action.files.save"},
{"voorkant":"Ctrl+K S","achterkant":"Save All","extra":"workbench.action.files.saveAll"},
{"voorkant":"Ctrl+Shift+S","achterkant":"Save As...","extra":"workbench.action.files.saveAs"},
{"voorkant":"Ctrl+F4","achterkant":"Close","extra":"workbench.action.closeActiveEditor"},
{"voorkant":"unassigned","achterkant":"Close Others","extra":"workbench.action.closeOtherEditors"},
{"voorkant":"Ctrl+K W","achterkant":"Close Group","extra":"workbench.action.closeEditorsInGroup"},
{"voorkant":"unassigned","achterkant":"Close Other Groups","extra":"workbench.action.closeEditorsInOtherGroups"},
{"voorkant":"unassigned","achterkant":"Close Group to Left","extra":"workbench.action.closeEditorsToTheLeft"},
{"voorkant":"unassigned","achterkant":"Close Group to Right","extra":"workbench.action.closeEditorsToTheRight"},
{"voorkant":"Ctrl+K Ctrl+W","achterkant":"Close All","extra":"workbench.action.closeAllEditors"},
{"voorkant":"Ctrl+Shift+T","achterkant":"Reopen Closed Editor","extra":"workbench.action.reopenClosedEditor"},
{"voorkant":"Ctrl+K Enter","achterkant":"Keep Open","extra":"workbench.action.keepEditor"},
{"voorkant":"Ctrl+K P","achterkant":"Copy Path of Active File","extra":"workbench.action.files.copyPathOfActiveFile"},
{"voorkant":"Ctrl+K R","achterkant":"Reveal Active File in Windows","extra":"workbench.action.files.revealActiveFileInWindows"},
{"voorkant":"Ctrl+K O","achterkant":"Show Opened File in New Window","extra":"workbench.action.files.showOpenedFileInNewWindow"},
{"voorkant":"unassigned","achterkant":"Compare Opened File With","extra":"workbench.files.action.compareFileWith"}
]
},
{"book": {
    "title": "vscode keyboard",
    "description": "Display"
  },
"page":[{"voorkant":"Key","achterkant":"Command","extra":"Command id"},
{"voorkant":"F11","achterkant":"Toggle Full Screen","extra":"workbench.action.toggleFullScreen"},
{"voorkant":"Ctrl+K Z","achterkant":"Toggle Zen Mode","extra":"workbench.action.toggleZenMode"},
{"voorkant":"Escape Escape","achterkant":"Leave Zen Mode","extra":"workbench.action.exitZenMode"},
{"voorkant":"Ctrl+=","achterkant":"Zoom in","extra":"workbench.action.zoomIn"},
{"voorkant":"Ctrl+-","achterkant":"Zoom out","extra":"workbench.action.zoomOut"},
{"voorkant":"Ctrl+Numpad0","achterkant":"Reset Zoom","extra":"workbench.action.zoomReset"},
{"voorkant":"Ctrl+B","achterkant":"Toggle Sidebar Visibility","extra":"workbench.action.toggleSidebarVisibility"},
{"voorkant":"Ctrl+Shift+E","achterkant":"Show Explorer / Toggle Focus","extra":"workbench.view.explorer"},
{"voorkant":"Ctrl+Shift+F","achterkant":"Show Search","extra":"workbench.view.search"},
{"voorkant":"Ctrl+Shift+G","achterkant":"Show Source Control","extra":"workbench.view.scm"},
{"voorkant":"Ctrl+Shift+D","achterkant":"Show Run","extra":"workbench.view.debug"},
{"voorkant":"Ctrl+Shift+X","achterkant":"Show Extensions","extra":"workbench.view.extensions"},
{"voorkant":"Ctrl+Shift+U","achterkant":"Show Output","extra":"workbench.action.output.toggleOutput"},
{"voorkant":"Ctrl+Q","achterkant":"Quick Open View","extra":"workbench.action.quickOpenView"},
{"voorkant":"Ctrl+Shift+C","achterkant":"Open New Command Prompt","extra":"workbench.action.terminal.openNativeConsole"},
{"voorkant":"Ctrl+Shift+V","achterkant":"Toggle Markdown Preview","extra":"markdown.showPreview"},
{"voorkant":"Ctrl+K V","achterkant":"Open Preview to the Side","extra":"markdown.showPreviewToSide"},
{"voorkant":"Ctrl+`","achterkant":"Toggle Integrated Terminal","extra":"workbench.action.terminal.toggleTerminal"}
]
},
{"book": {
    "title": "vscode keyboard",
    "description": "Search"
  },
"page":[{"voorkant":"Key","achterkant":"Command","extra":"Command id"},
{"voorkant":"Ctrl+Shift+F","achterkant":"Show Search","extra":"workbench.view.search"},
{"voorkant":"Ctrl+Shift+H","achterkant":"Replace in Files","extra":"workbench.action.replaceInFiles"},
{"voorkant":"Alt+C","achterkant":"Toggle Match Case","extra":"toggleSearchCaseSensitive"},
{"voorkant":"Alt+W","achterkant":"Toggle Match Whole Word","extra":"toggleSearchWholeWord"},
{"voorkant":"Alt+R","achterkant":"Toggle Use Regular Expression","extra":"toggleSearchRegex"},
{"voorkant":"Ctrl+Shift+J","achterkant":"Toggle Search Details","extra":"workbench.action.search.toggleQueryDetails"},
{"voorkant":"F4","achterkant":"Focus Next Search Result","extra":"search.action.focusNextSearchResult"},
{"voorkant":"Shift+F4","achterkant":"Focus Previous Search Result","extra":"search.action.focusPreviousSearchResult"},
{"voorkant":"Down","achterkant":"Show Next Search Term","extra":"history.showNext"},
{"voorkant":"Up","achterkant":"Show Previous Search Term","extra":"history.showPrevious"}
]
},
{"book": {
    "title": "vscode keyboard",
    "description": "Preferences"
  },
"page":[{"voorkant":"Key","achterkant":"Command","extra":"Command id"},
{"voorkant":"Ctrl+,","achterkant":"Open Settings","extra":"workbench.action.openSettings"},
{"voorkant":"unassigned","achterkant":"Open Workspace Settings","extra":"workbench.action.openWorkspaceSettings"},
{"voorkant":"Ctrl+K Ctrl+S","achterkant":"Open Keyboard Shortcuts","extra":"workbench.action.openGlobalKeybindings"},
{"voorkant":"unassigned","achterkant":"Open User Snippets","extra":"workbench.action.openSnippets"},
{"voorkant":"Ctrl+K Ctrl+T","achterkant":"Select Color Theme","extra":"workbench.action.selectTheme"},
{"voorkant":"unassigned","achterkant":"Configure Display Language","extra":"workbench.action.configureLocale"}
]
},
{"book": {
    "title": "vscode keyboard",
    "description": "Debug"
  },
"page":[{"voorkant":"Key","achterkant":"Command","extra":"Command id"},
{"voorkant":"F9","achterkant":"Toggle Breakpoint","extra":"editor.debug.action.toggleBreakpoint"},
{"voorkant":"F5","achterkant":"Start","extra":"workbench.action.debug.start"},
{"voorkant":"F5","achterkant":"Continue","extra":"workbench.action.debug.continue"},
{"voorkant":"Ctrl+F5","achterkant":"Start (without debugging)","extra":"workbench.action.debug.run"},
{"voorkant":"F6","achterkant":"Pause","extra":"workbench.action.debug.pause"},
{"voorkant":"F11","achterkant":"Step Into","extra":"workbench.action.debug.stepInto"},
{"voorkant":"Shift+F11","achterkant":"Step Out","extra":"workbench.action.debug.stepOut"},
{"voorkant":"F10","achterkant":"Step Over","extra":"workbench.action.debug.stepOver"},
{"voorkant":"Shift+F5","achterkant":"Stop","extra":"workbench.action.debug.stop"},
{"voorkant":"Ctrl+K Ctrl+I","achterkant":"Show Hover","extra":"editor.debug.action.showDebugHover"}
]
},
{"book": {
    "title": "vscode keyboard",
    "description": "Tasks"
  },
"page":[{"voorkant":"Key","achterkant":"Command","extra":"Command id"},
{"voorkant":"Ctrl+Shift+B","achterkant":"Run Build Task","extra":"workbench.action.tasks.build"},
{"voorkant":"unassigned","achterkant":"Run Test Task","extra":"workbench.action.tasks.test"}
]
},
{"book": {
    "title": "vscode keyboard",
    "description": "Extensions"
  },
"page":[{"voorkant":"Key","achterkant":"Command","extra":"Command id"},
{"voorkant":"unassigned","achterkant":"Install Extension","extra":"workbench.extensions.action.installExtension"},
{"voorkant":"unassigned","achterkant":"Show Installed Extensions","extra":"workbench.extensions.action.showInstalledExtensions"},
{"voorkant":"unassigned","achterkant":"Show Outdated Extensions","extra":"workbench.extensions.action.listOutdatedExtensions"},
{"voorkant":"unassigned","achterkant":"Show Recommended Extensions","extra":"workbench.extensions.action.showRecommendedExtensions"},
{"voorkant":"unassigned","achterkant":"Show Popular Extensions","extra":"workbench.extensions.action.showPopularExtensions"},
{"voorkant":"unassigned","achterkant":"Update All Extensions","extra":"workbench.extensions.action.updateAllExtensions"}
]}]''';
